<a href="https://colab.research.google.com/github/sitthatkaja/ParkinsonAIModel/blob/main/%5BClassification%5D_Non_NormalFA_Frame_Average.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Classification] Non NormalFA Frame Average

This colab is a code for Classification (Parkinson or not) for ``` Frame Average in 3 Facial Action Scenario following: Non-Smile, Smile, and Combine``` introducing methodology.

***Note: if you have any problem please check in my github: https://github.com/sitthatkaja/ParkinsonAIModel***

---

## 1. Data Input
---

This section you need to input data form data collect in github. This setep is depend on user. You can use  ``` Google sheet link with google Drive ``` to import Data.

***Note: This section is not to shown because a privacy of account.***

## 2. Data Preprocessing
---

Form my input this is sliding video to half for  `3 Facial Action Scenarios following: Non-Smile, Smile, and Combine` that is mean the data should be counting of half it (709 Columns in Frame Average)


***note: This method have something wrong or error of colab including: number of column. you can ignore it.***

In [ ]:
dfss = [globals()[f'df{i}'] for i in range(1, len(dfs) + 1)]

In [ ]:
print(len(dfss))

400

In [ ]:
# สร้าง DataFrame ว่างเพื่อเก็บผลลัพธ์
mean_df = pd.DataFrame()

# ลูปผ่านแต่ละ DataFrame และคำนวณค่าเฉลี่ย
for i, df in enumerate(dfss, start=1):
    mean_series = df.mean()  # คำนวณค่าเฉลี่ยของแต่ละคอลัมน์ใน DataFrame
    mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย

transposed_mean_df = mean_df.T
transposed_mean_df

/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย
/tmp/ipython-input-20-2774443378.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  mean_df[f'df{i}_mean'] = mean_series  # เพิ่มแถวใหม่ใน mean_df เพื่อเก็บค่าเฉลี่ย

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
df1_mean,75.5,0.0,2.483333,0.98,1.0,0.137142,0.195839,-0.969756,-0.164832,0.252987,...,0.000000,0.0,0.900000,0.000000,0.906667,0.626667,0.006667,0.000000,0.000000,1.000000
df2_mean,75.5,0.0,2.483333,0.98,1.0,0.191172,0.223884,-0.955521,-0.101594,0.239615,...,0.000000,0.0,0.686667,0.000000,0.760000,0.500000,0.000000,0.000000,0.000000,1.000000
df3_mean,75.5,0.0,2.483333,0.98,1.0,0.158266,0.262902,-0.951316,-0.090683,0.252678,...,0.000000,0.0,0.993333,0.000000,0.780000,0.713333,0.000000,0.000000,0.753333,0.166667
df4_mean,75.5,0.0,2.483333,0.98,1.0,0.136185,0.262256,-0.951555,-0.125984,0.332941,...,0.000000,0.0,0.846667,0.000000,0.953333,1.000000,0.046667,0.080000,0.000000,1.000000
df5_mean,75.5,0.0,2.483333,0.98,1.0,0.208775,0.248445,-0.945630,-0.083583,0.299747,...,0.000000,0.0,1.000000,0.000000,0.340000,0.820000,0.026667,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
df396_mean,75.0,0.0,2.466664,0.98,1.0,0.028003,0.223339,-0.974164,-0.058269,0.179758,...,0.771812,0.0,0.765101,0.563758,1.000000,0.731544,0.805369,0.000000,0.000000,1.000000
df397_mean,75.0,0.0,2.466664,0.98,1.0,0.020730,0.186632,-0.982083,-0.071863,0.154150,...,0.751678,0.0,0.979866,0.617450,0.798658,0.020134,0.510067,0.000000,0.046980,1.000000
df398_mean,75.0,0.0,2.466664,0.98,1.0,0.023677,0.199116,-0.979576,-0.076674,0.165542,...,0.805369,0.0,0.892617,0.731544,1.000000,0.214765,0.859060,0.000000,0.013423,1.000000
df399_mean,75.0,0.0,2.466664,0.98,1.0,0.034209,0.217480,-0.975317,-0.071833,0.177992,...,0.798658,0.0,0.798658,0.530201,1.000000,0.697987,0.832215,0.013423,0.006711,1.000000
df400_mean,75.0,0.0,2.466664,0.98,1.0,0.030161,0.223669,-0.974126,-0.059761,0.177021,...,0.986577,0.0,0.953020,0.510067,1.000000,0.959732,1.000000,0.000000,0.000000,1.000000

In [ ]:
result = transposed_mean_df.iloc[:,5:]
result = result.reset_index(drop=True)
result.head()

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,eye_lmk_x_0,eye_lmk_x_1,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,0.137142,0.195839,-0.969756,-0.164832,0.252987,-0.952254,-0.014487,0.229407,450.116000,456.029333,...,0.0,0.0,0.900000,0.0,0.906667,0.626667,0.006667,0.00,0.000000,1.000000
1,0.191172,0.223884,-0.955521,-0.101594,0.239615,-0.964994,0.046553,0.236833,385.327333,392.010000,...,0.0,0.0,0.686667,0.0,0.760000,0.500000,0.000000,0.00,0.000000,1.000000
2,0.158266,0.262902,-0.951316,-0.090683,0.252678,-0.962704,0.035287,0.263187,479.235333,485.786667,...,0.0,0.0,0.993333,0.0,0.780000,0.713333,0.000000,0.00,0.753333,0.166667
3,0.136185,0.262256,-0.951555,-0.125984,0.332941,-0.933328,0.005567,0.305893,364.622000,368.491333,...,0.0,0.0,0.846667,0.0,0.953333,1.000000,0.046667,0.08,0.000000,1.000000
4,0.208775,0.248445,-0.945630,-0.083583,0.299747,-0.949814,0.065913,0.281507,374.408000,380.262000,...,0.0,0.0,1.000000,0.0,0.340000,0.820000,0.026667,0.00,0.000000,1.000000

In [ ]:
df

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.98,1,0.037639,0.247780,-0.968085,-0.038300,0.204927,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,2,0,0.033,0.98,1,0.030746,0.229817,-0.972748,-0.057198,0.180724,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
2,3,0,0.067,0.98,1,0.031129,0.218694,-0.975297,-0.057968,0.172753,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
3,4,0,0.100,0.98,1,0.041732,0.231383,-0.971967,-0.061909,0.181412,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,5,0,0.133,0.98,1,0.036508,0.220392,-0.974728,-0.065024,0.174557,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,0,4.800,0.98,1,0.032671,0.220304,-0.974884,-0.075168,0.184824,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
145,146,0,4.833,0.98,1,0.039893,0.223654,-0.973852,-0.068652,0.192179,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
146,147,0,4.867,0.98,1,0.039788,0.221871,-0.974264,-0.066135,0.184205,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
147,148,0,4.900,0.98,1,0.047761,0.215772,-0.975275,-0.064655,0.179834,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
148,149,0,4.933,0.98,1,0.046660,0.212834,-0.975974,-0.065017,0.186811,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

## 3. Modeling
---
This section is Modeling when you prepare data form data preprocessing. This method, You should to try setup form other side and coding following: PCA and 3 Models.

***Note: This section in for experimental for all. It's means some value is non-using for report.***

3.1 NO PCA

---

In [ ]:
status = df[['Paror1Healthy0', 'kfold','ForS']]
status

     Paror1Healthy0  kfold  ForS
0                 1      1     1
1                 1      1     1
2                 1      1     1
3                 1      1     1
4                 1      1     1
..              ...    ...   ...
395               0      5     2
396               0      5     2
397               0      5     2
398               0      5     2
399               0      5     2

[400 rows x 3 columns]

In [ ]:
full = pd.concat([status,result], axis=1)
full

,Paror1Healthy0,kfold,ForS,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,1,1,0.137142,0.195839,-0.969756,-0.164832,0.252987,-0.952254,-0.014487,...,0.000000,0.0,0.900000,0.000000,0.906667,0.626667,0.006667,0.000000,0.000000,1.000000
1,1,1,1,0.191172,0.223884,-0.955521,-0.101594,0.239615,-0.964994,0.046553,...,0.000000,0.0,0.686667,0.000000,0.760000,0.500000,0.000000,0.000000,0.000000,1.000000
2,1,1,1,0.158266,0.262902,-0.951316,-0.090683,0.252678,-0.962704,0.035287,...,0.000000,0.0,0.993333,0.000000,0.780000,0.713333,0.000000,0.000000,0.753333,0.166667
3,1,1,1,0.136185,0.262256,-0.951555,-0.125984,0.332941,-0.933328,0.005567,...,0.000000,0.0,0.846667,0.000000,0.953333,1.000000,0.046667,0.080000,0.000000,1.000000
4,1,1,1,0.208775,0.248445,-0.945630,-0.083583,0.299747,-0.949814,0.065913,...,0.000000,0.0,1.000000,0.000000,0.340000,0.820000,0.026667,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,5,2,0.028003,0.223339,-0.974164,-0.058269,0.179758,-0.981747,-0.015477,...,0.771812,0.0,0.765101,0.563758,1.000000,0.731544,0.805369,0.000000,0.000000,1.000000
396,0,5,2,0.020730,0.186632,-0.982083,-0.071863,0.154150,-0.985330,-0.025960,...,0.751678,0.0,0.979866,0.617450,0.798658,0.020134,0.510067,0.000000,0.046980,1.000000
397,0,5,2,0.023677,0.199116,-0.979576,-0.076674,0.165542,-0.982998,-0.027040,...,0.805369,0.0,0.892617,0.731544,1.000000,0.214765,0.859060,0.000000,0.013423,1.000000
398,0,5,2,0.034209,0.217480,-0.975317,-0.071833,0.177992,-0.981271,-0.019201,...,0.798658,0.0,0.798658,0.530201,1.000000,0.697987,0.832215,0.013423,0.006711,1.000000
399,0,5,2,0.030161,0.223669,-0.974126,-0.059761,0.177021,-0.982303,-0.015148,...,0.986577,0.0,0.953020,0.510067,1.000000,0.959732,1.000000,0.000000,0.000000,1.000000

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
# แยก full ตาม ForS
full_first = full[full['ForS'] == 1].reset_index(drop=True)
full_second = full[full['ForS'] == 2].reset_index(drop=True)
# full เดิมคือทั้งครึ่งแรกและครึ่งหลัง

In [ ]:
def run_kfold_no_pca(df, target_col='Paror1Healthy0', kfold_col='kfold'):
    models = {
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel="linear"),
    "XGBoost": xgb.XGBClassifier()
    }

    results = {name: {
        "accuracy": [], "precision": [], "recall": [], "f1": [],
        "TP": [], "TN": [], "FP": [], "FN": []
    } for name in models}

    for fold in range(1, 6):
        print(f"\n===== Fold {fold} =====")
        df_train = df[df[kfold_col] != fold].reset_index(drop=True)
        df_valid = df[df[kfold_col] == fold].reset_index(drop=True)

        # ดรอป target, kfold, ForS (ถ้ามี) ออกจาก X
        drop_cols = [target_col, kfold_col]
        if 'ForS' in df.columns:
            drop_cols.append('ForS')

        X_train = df_train.drop(columns=drop_cols)
        y_train = df_train[target_col]
        X_valid = df_valid.drop(columns=drop_cols)
        y_valid = df_valid[target_col]

        for name, model in models.items():
            model.fit(X_train, y_train)
            preds = model.predict(X_valid)

            accuracy = accuracy_score(y_valid, preds)
            precision = precision_score(y_valid, preds, average='binary')
            recall = recall_score(y_valid, preds, average='binary')
            f1 = f1_score(y_valid, preds, average='binary')
            tn, fp, fn, tp = confusion_matrix(y_valid, preds).ravel()

            results[name]["accuracy"].append(accuracy)
            results[name]["precision"].append(precision)
            results[name]["recall"].append(recall)
            results[name]["f1"].append(f1)
            results[name]["TP"].append(tp)
            results[name]["TN"].append(tn)
            results[name]["FP"].append(fp)
            results[name]["FN"].append(fn)

            print(f"{name}: Accuracy={accuracy:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
            print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

    # สรุปค่าเฉลี่ยแต่ละโมเดล
    print("\n===== Average Performance Across 5 Folds =====")
    for name in models:
        avg_acc = sum(results[name]["accuracy"]) / 5
        avg_prec = sum(results[name]["precision"]) / 5
        avg_rec = sum(results[name]["recall"]) / 5
        avg_f1 = sum(results[name]["f1"]) / 5
        avg_tp = sum(results[name]["TP"]) / 5
        avg_tn = sum(results[name]["TN"]) / 5
        avg_fp = sum(results[name]["FP"]) / 5
        avg_fn = sum(results[name]["FN"]) / 5

        print(f"{name}:")
        print(f"  Accuracy={avg_acc:.4f}, Precision={avg_prec:.4f}, Recall={avg_rec:.4f}, F1 Score={avg_f1:.4f}")
        print(f"  Avg TP={avg_tp:.1f}, TN={avg_tn:.1f}, FP={avg_fp:.1f}, FN={avg_fn:.1f}")

In [ ]:
print("\n### K-Fold (No PCA) - full_first ###")
run_kfold_no_pca(full_first)

### K-Fold (No PCA) - full_first ###

===== Fold 1 =====
RandomForest: Accuracy=0.7750, Precision=1.0000, Recall=0.5500, F1=0.7097
        TP=11, TN=20, FP=0, FN=9
SVM: Accuracy=0.7250, Precision=0.9091, Recall=0.5000, F1=0.6452
        TP=10, TN=19, FP=1, FN=10
XGBoost: Accuracy=0.7250, Precision=0.7368, Recall=0.7000, F1=0.7179
        TP=14, TN=15, FP=5, FN=6

===== Fold 2 =====
RandomForest: Accuracy=0.8000, Precision=0.7500, Recall=0.9000, F1=0.8182
        TP=18, TN=14, FP=6, FN=2
SVM: Accuracy=0.4750, Precision=0.4615, Recall=0.3000, F1=0.3636
        TP=6, TN=13, FP=7, FN=14
XGBoost: Accuracy=0.7250, Precision=0.7143, Recall=0.7500, F1=0.7317
        TP=15, TN=14, FP=6, FN=5

===== Fold 3 =====
RandomForest: Accuracy=0.5500, Precision=0.5556, Recall=0.5000, F1=0.5263
        TP=10, TN=12, FP=8, FN=10
SVM: Accuracy=0.2500, Precision=0.3333, Recall=0.5000, F1=0.4000
        TP=10, TN=0, FP=20, FN=10
XGBoost: Accuracy=0.5500, Precision=0.5500, Recall=0.5500, F1=0.5500
        TP=11, TN=11, FP=9, FN=9

===== Fold 4 =====
RandomForest: Accuracy=0.5750, Precision=0.6154, Recall=0.4000, F1=0.4848
        TP=8, TN=15, FP=5, FN=12
SVM: Accuracy=0.4750, Precision=0.4444, Recall=0.2000, F1=0.2759
        TP=4, TN=15, FP=5, FN=16
XGBoost: Accuracy=0.4750, Precision=0.4444, Recall=0.2000, F1=0.2759
        TP=4, TN=15, FP=5, FN=16

===== Fold 5 =====
RandomForest: Accuracy=0.4000, Precision=0.3750, Recall=0.3000, F1=0.3333
        TP=6, TN=10, FP=10, FN=14
SVM: Accuracy=0.4000, Precision=0.3571, Recall=0.2500, F1=0.2941
        TP=5, TN=11, FP=9, FN=15
XGBoost: Accuracy=0.5000, Precision=0.5000, Recall=0.3500, F1=0.4118
        TP=7, TN=13, FP=7, FN=13

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6200, Precision=0.6592, Recall=0.5300, F1 Score=0.5745
  Avg TP=10.6, TN=14.2, FP=5.8, FN=9.4
SVM:
  Accuracy=0.4650, Precision=0.5011, Recall=0.3500, F1 Score=0.3958
  Avg TP=7.0, TN=11.6, FP=8.4, FN=13.0
XGBoost:
  Accuracy=0.5950, Precision=0.5891, Recall=0.5100, F1 Score=0.5375
  Avg TP=10.2, TN=13.6, FP=6.4, FN=9.8

In [ ]:
print("\n### K-Fold (No PCA) - full_second ###")
run_kfold_no_pca(full_second)

### K-Fold (No PCA) - full_second ###

===== Fold 1 =====
RandomForest: Accuracy=0.7500, Precision=1.0000, Recall=0.5000, F1=0.6667
        TP=10, TN=20, FP=0, FN=10
SVM: Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9
XGBoost: Accuracy=0.9500, Precision=0.9500, Recall=0.9500, F1=0.9500
        TP=19, TN=19, FP=1, FN=1

===== Fold 2 =====
RandomForest: Accuracy=0.8250, Precision=0.7826, Recall=0.9000, F1=0.8372
        TP=18, TN=15, FP=5, FN=2
SVM: Accuracy=0.7750, Precision=0.7895, Recall=0.7500, F1=0.7692
        TP=15, TN=16, FP=4, FN=5
XGBoost: Accuracy=0.7750, Precision=0.7895, Recall=0.7500, F1=0.7692
        TP=15, TN=16, FP=4, FN=5

===== Fold 3 =====
RandomForest: Accuracy=0.4000, Precision=0.4231, Recall=0.5500, F1=0.4783
        TP=11, TN=5, FP=15, FN=9
SVM: Accuracy=0.6250, Precision=0.6000, Recall=0.7500, F1=0.6667
        TP=15, TN=10, FP=10, FN=5
XGBoost: Accuracy=0.7500, Precision=0.7500, Recall=0.7500, F1=0.7500
        TP=15, TN=15, FP=5, FN=5

===== Fold 4 =====
RandomForest: Accuracy=0.6000, Precision=0.6429, Recall=0.4500, F1=0.5294
        TP=9, TN=15, FP=5, FN=11
SVM: Accuracy=0.6500, Precision=0.8750, Recall=0.3500, F1=0.5000
        TP=7, TN=19, FP=1, FN=13
XGBoost: Accuracy=0.5250, Precision=0.5455, Recall=0.3000, F1=0.3871
        TP=6, TN=15, FP=5, FN=14

===== Fold 5 =====
RandomForest: Accuracy=0.4250, Precision=0.4286, Recall=0.4500, F1=0.4390
        TP=9, TN=8, FP=12, FN=11
SVM: Accuracy=0.3250, Precision=0.3333, Recall=0.3500, F1=0.3415
        TP=7, TN=6, FP=14, FN=13
XGBoost: Accuracy=0.6250, Precision=0.6190, Recall=0.6500, F1=0.6341
        TP=13, TN=12, FP=8, FN=7

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6000, Precision=0.6554, Recall=0.5700, F1 Score=0.5901
  Avg TP=11.4, TN=12.6, FP=7.4, FN=8.6
SVM:
  Accuracy=0.5800, Precision=0.6243, Recall=0.5500, F1 Score=0.5628
  Avg TP=11.0, TN=12.2, FP=7.8, FN=9.0
XGBoost:
  Accuracy=0.7250, Precision=0.7308, Recall=0.6800, F1 Score=0.6981
  Avg TP=13.6, TN=15.4, FP=4.6, FN=6.4

In [ ]:
print("\n### K-Fold (No PCA) - full (ทั้งตาราง) ###")
run_kfold_no_pca(full)

### K-Fold (No PCA) - full (ทั้งตาราง) ###

===== Fold 1 =====
RandomForest: Accuracy=0.7500, Precision=1.0000, Recall=0.5000, F1=0.6667
        TP=20, TN=40, FP=0, FN=20
SVM: Accuracy=0.6250, Precision=0.6389, Recall=0.5750, F1=0.6053
        TP=23, TN=27, FP=13, FN=17
XGBoost: Accuracy=0.7500, Precision=0.8125, Recall=0.6500, F1=0.7222
        TP=26, TN=34, FP=6, FN=14

===== Fold 2 =====
RandomForest: Accuracy=0.7625, Precision=0.7561, Recall=0.7750, F1=0.7654
        TP=31, TN=30, FP=10, FN=9
SVM: Accuracy=0.6125, Precision=0.6667, Recall=0.4500, F1=0.5373
        TP=18, TN=31, FP=9, FN=22
XGBoost: Accuracy=0.7875, Precision=0.8286, Recall=0.7250, F1=0.7733
        TP=29, TN=34, FP=6, FN=11

===== Fold 3 =====
RandomForest: Accuracy=0.5125, Precision=0.5128, Recall=0.5000, F1=0.5063
        TP=20, TN=21, FP=19, FN=20
SVM: Accuracy=0.3000, Precision=0.2895, Recall=0.2750, F1=0.2821
        TP=11, TN=13, FP=27, FN=29
XGBoost: Accuracy=0.5000, Precision=0.5000, Recall=0.5250, F1=0.5122
        TP=21, TN=19, FP=21, FN=19

===== Fold 4 =====
RandomForest: Accuracy=0.5875, Precision=0.6296, Recall=0.4250, F1=0.5075
        TP=17, TN=30, FP=10, FN=23
SVM: Accuracy=0.6000, Precision=0.6538, Recall=0.4250, F1=0.5152
        TP=17, TN=31, FP=9, FN=23
XGBoost: Accuracy=0.4625, Precision=0.4118, Recall=0.1750, F1=0.2456
        TP=7, TN=30, FP=10, FN=33

===== Fold 5 =====
RandomForest: Accuracy=0.3250, Precision=0.2941, Recall=0.2500, F1=0.2703
        TP=10, TN=16, FP=24, FN=30
SVM: Accuracy=0.2875, Precision=0.2258, Recall=0.1750, F1=0.1972
        TP=7, TN=16, FP=24, FN=33
XGBoost: Accuracy=0.6125, Precision=0.6286, Recall=0.5500, F1=0.5867
        TP=22, TN=27, FP=13, FN=18

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.5875, Precision=0.6385, Recall=0.4900, F1 Score=0.5432
  Avg TP=19.6, TN=27.4, FP=12.6, FN=20.4
SVM:
  Accuracy=0.4850, Precision=0.4949, Recall=0.3800, F1 Score=0.4274
  Avg TP=15.2, TN=23.6, FP=16.4, FN=24.8
XGBoost:
  Accuracy=0.6225, Precision=0.6363, Recall=0.5250, F1 Score=0.5680
  Avg TP=21.0, TN=28.8, FP=11.2, FN=19.0

---

---
#### 3.2 PCA 95% and 98% variance

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:

import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import numpy as np

def run_kfold_with_pca(df, target_col='Paror1Healthy0', kfold_col='kfold', variances=[0.95, 0.98]):
    models = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
        "SVM (Linear)": SVC(kernel='linear'),
        "XGBoost": xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
    }

    for var in variances:
        print(f"\n===== PCA with Explained Variance = {var} =====")
        results = {name: [] for name in models.keys()}

        for fold in range(1, 6):
            print(f"\n===== Fold {fold} =====")
            train_df = df[df[kfold_col] != fold].reset_index(drop=True)
            valid_df = df[df[kfold_col] == fold].reset_index(drop=True)

            drop_cols = [target_col, kfold_col]
            if 'ForS' in df.columns:
                drop_cols.append('ForS')

            X_train = train_df.drop(columns=drop_cols).values
            y_train = train_df[target_col].values
            X_valid = valid_df.drop(columns=drop_cols).values
            y_valid = valid_df[target_col].values

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_valid_scaled = scaler.transform(X_valid)

            pca = PCA(n_components=var)
            X_train_pca = pca.fit_transform(X_train_scaled)
            X_valid_pca = pca.transform(X_valid_scaled)

            n_components_used = X_train_pca.shape[1]
            print(f"  -> Components to reach {var*100:.0f}% variance: {n_components_used} components")

            for name, model in models.items():
                model.fit(X_train_pca, y_train)
                y_pred = model.predict(X_valid_pca)

                acc = accuracy_score(y_valid, y_pred)
                f1 = f1_score(y_valid, y_pred)
                recall = recall_score(y_valid, y_pred)
                precision = precision_score(y_valid, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_valid, y_pred).ravel()

                results[name].append({
                    'fold': fold,
                    'n_components': n_components_used,
                    'accuracy': acc,
                    'f1_score': f1,
                    'recall': recall,
                    'precision': precision,
                    'tn': tn,
                    'fp': fp,
                    'fn': fn,
                    'tp': tp
                })

                print(f"{name}: Accuracy={acc:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
                print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

        # สรุปค่าเฉลี่ย
        print(f"\n===== Average Performance Across 5 Folds (Explained Variance = {var}) =====")
        for name in results:
            accuracies = [r['accuracy'] for r in results[name]]
            f1s = [r['f1_score'] for r in results[name]]
            recalls = [r['recall'] for r in results[name]]
            precisions = [r['precision'] for r in results[name]]
            tns = [r['tn'] for r in results[name]]
            fps = [r['fp'] for r in results[name]]
            fns = [r['fn'] for r in results[name]]
            tps = [r['tp'] for r in results[name]]
            components = [r['n_components'] for r in results[name]]

            print(f"{name}:")
            print(f"  Accuracy={np.mean(accuracies):.4f}, Precision={np.mean(precisions):.4f}, Recall={np.mean(recalls):.4f}, F1 Score={np.mean(f1s):.4f}")
            print(f"  Avg TP={np.mean(tps):.1f}, TN={np.mean(tns):.1f}, FP={np.mean(fps):.1f}, FN={np.mean(fns):.1f}")
            print(f"  Avg PCA Components Used: {np.mean(components):.1f}")

In [ ]:
print("\n### K-Fold + PCA - full_first ###")
run_kfold_with_pca(full_first)

### K-Fold + PCA - full_first ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 11 components
RandomForest: Accuracy=0.8500, Precision=0.9375, Recall=0.7500, F1=0.8333
        TP=15, TN=19, FP=1, FN=5
SVM (Linear): Accuracy=0.9250, Precision=1.0000, Recall=0.8500, F1=0.9189
        TP=17, TN=20, FP=0, FN=3
XGBoost: Accuracy=0.9000, Precision=0.9444, Recall=0.8500, F1=0.8947
        TP=17, TN=19, FP=1, FN=3

===== Fold 2 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:43] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 95% variance: 12 components
RandomForest: Accuracy=0.5750, Precision=0.7143, Recall=0.2500, F1=0.3704
        TP=5, TN=18, FP=2, FN=15
SVM (Linear): Accuracy=0.5250, Precision=0.5263, Recall=0.5000, F1=0.5128
        TP=10, TN=11, FP=9, FN=10
XGBoost: Accuracy=0.5750, Precision=0.5882, Recall=0.5000, F1=0.5405
        TP=10, TN=13, FP=7, FN=10

===== Fold 3 =====
  -> Components to reach 95% variance: 12 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:43] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.4000, Precision=0.4333, Recall=0.6500, F1=0.5200
        TP=13, TN=3, FP=17, FN=7
SVM (Linear): Accuracy=0.6500, Precision=0.6250, Recall=0.7500, F1=0.6818
        TP=15, TN=11, FP=9, FN=5
XGBoost: Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9

===== Fold 4 =====
  -> Components to reach 95% variance: 11 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:43] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5250, Precision=0.6667, Recall=0.1000, F1=0.1739
        TP=2, TN=19, FP=1, FN=18
SVM (Linear): Accuracy=0.6250, Precision=0.7778, Recall=0.3500, F1=0.4828
        TP=7, TN=18, FP=2, FN=13
XGBoost: Accuracy=0.6250, Precision=0.8571, Recall=0.3000, F1=0.4444
        TP=6, TN=19, FP=1, FN=14

===== Fold 5 =====
  -> Components to reach 95% variance: 11 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:44] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.4250, Precision=0.4348, Recall=0.5000, F1=0.4651
        TP=10, TN=7, FP=13, FN=10
SVM (Linear): Accuracy=0.6250, Precision=0.6000, Recall=0.7500, F1=0.6667
        TP=15, TN=10, FP=10, FN=5
XGBoost: Accuracy=0.4500, Precision=0.4583, Recall=0.5500, F1=0.5000
        TP=11, TN=7, FP=13, FN=9

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.5550, Precision=0.6373, Recall=0.4500, F1 Score=0.4725
  Avg TP=9.0, TN=13.2, FP=6.8, FN=11.0
  Avg PCA Components Used: 11.4
SVM (Linear):
  Accuracy=0.6700, Precision=0.7058, Recall=0.6400, F1 Score=0.6526
  Avg TP=12.8, TN=14.0, FP=6.0, FN=7.2
  Avg PCA Components Used: 11.4
XGBoost:
  Accuracy=0.6150, Precision=0.6744, Recall=0.5500, F1 Score=0.5833
  Avg TP=11.0, TN=13.6, FP=6.4, FN=9.0
  Avg PCA Components Used: 11.4

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 20 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:44] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.9500, Precision=0.9500, Recall=0.9500, F1=0.9500
        TP=19, TN=19, FP=1, FN=1
SVM (Linear): Accuracy=0.7750, Precision=0.7895, Recall=0.7500, F1=0.7692
        TP=15, TN=16, FP=4, FN=5
XGBoost: Accuracy=0.8000, Precision=0.9286, Recall=0.6500, F1=0.7647
        TP=13, TN=19, FP=1, FN=7

===== Fold 2 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:45] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 98% variance: 20 components
RandomForest: Accuracy=0.5250, Precision=0.5455, Recall=0.3000, F1=0.3871
        TP=6, TN=15, FP=5, FN=14
SVM (Linear): Accuracy=0.5750, Precision=0.5789, Recall=0.5500, F1=0.5641
        TP=11, TN=12, FP=8, FN=9
XGBoost: Accuracy=0.4750, Precision=0.4615, Recall=0.3000, F1=0.3636
        TP=6, TN=13, FP=7, FN=14

===== Fold 3 =====
  -> Components to reach 98% variance: 21 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:45] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5750, Precision=0.5455, Recall=0.9000, F1=0.6792
        TP=18, TN=5, FP=15, FN=2
SVM (Linear): Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9
XGBoost: Accuracy=0.5250, Precision=0.5185, Recall=0.7000, F1=0.5957
        TP=14, TN=7, FP=13, FN=6

===== Fold 4 =====
  -> Components to reach 98% variance: 20 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:45] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.6000, Precision=0.6667, Recall=0.4000, F1=0.5000
        TP=8, TN=16, FP=4, FN=12
SVM (Linear): Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9
XGBoost: Accuracy=0.6500, Precision=0.6667, Recall=0.6000, F1=0.6316
        TP=12, TN=14, FP=6, FN=8

===== Fold 5 =====
  -> Components to reach 98% variance: 20 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:46] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9
SVM (Linear): Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9
XGBoost: Accuracy=0.4000, Precision=0.4167, Recall=0.5000, F1=0.4545
        TP=10, TN=6, FP=14, FN=10

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.6350, Precision=0.6463, Recall=0.6200, F1 Score=0.6106
  Avg TP=12.4, TN=13.0, FP=7.0, FN=7.6
  Avg PCA Components Used: 20.2
SVM (Linear):
  Accuracy=0.6350, Precision=0.6534, Recall=0.5900, F1 Score=0.6184
  Avg TP=11.8, TN=13.6, FP=6.4, FN=8.2
  Avg PCA Components Used: 20.2
XGBoost:
  Accuracy=0.5700, Precision=0.5984, Recall=0.5500, F1 Score=0.5620
  Avg TP=11.0, TN=11.8, FP=8.2, FN=9.0
  Avg PCA Components Used: 20.2

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:46] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

In [ ]:
print("\n### K-Fold + PCA - full_second ###")
run_kfold_with_pca(full_second)

### K-Fold + PCA - full_second ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 11 components
RandomForest: Accuracy=0.9250, Precision=1.0000, Recall=0.8500, F1=0.9189
        TP=17, TN=20, FP=0, FN=3
SVM (Linear): Accuracy=1.0000, Precision=1.0000, Recall=1.0000, F1=1.0000
        TP=20, TN=20, FP=0, FN=0
XGBoost: Accuracy=0.9000, Precision=1.0000, Recall=0.8000, F1=0.8889
        TP=16, TN=20, FP=0, FN=4

===== Fold 2 =====
  -> Components to reach 95% variance: 11 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:46] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9
SVM (Linear): Accuracy=0.5500, Precision=0.5455, Recall=0.6000, F1=0.5714
        TP=12, TN=10, FP=10, FN=8
XGBoost: Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9

===== Fold 3 =====
  -> Components to reach 95% variance: 12 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:47] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.5000, F1=0.5000
        TP=10, TN=10, FP=10, FN=10
SVM (Linear): Accuracy=0.6250, Precision=0.6667, Recall=0.5000, F1=0.5714
        TP=10, TN=15, FP=5, FN=10
XGBoost: Accuracy=0.4000, Precision=0.3750, Recall=0.3000, F1=0.3333
        TP=6, TN=10, FP=10, FN=14

===== Fold 4 =====
  -> Components to reach 95% variance: 11 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:47] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.6750, Precision=0.8182, Recall=0.4500, F1=0.5806
        TP=9, TN=18, FP=2, FN=11
SVM (Linear): Accuracy=0.7250, Precision=1.0000, Recall=0.4500, F1=0.6207
        TP=9, TN=20, FP=0, FN=11
XGBoost: Accuracy=0.6250, Precision=1.0000, Recall=0.2500, F1=0.4000
        TP=5, TN=20, FP=0, FN=15

===== Fold 5 =====
  -> Components to reach 95% variance: 10 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:47] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.6000, Precision=0.5769, Recall=0.7500, F1=0.6522
        TP=15, TN=9, FP=11, FN=5
SVM (Linear): Accuracy=0.6250, Precision=0.5714, Recall=1.0000, F1=0.7273
        TP=20, TN=5, FP=15, FN=0
XGBoost: Accuracy=0.6500, Precision=0.6250, Recall=0.7500, F1=0.6818
        TP=15, TN=11, FP=9, FN=5

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.6700, Precision=0.7165, Recall=0.6200, F1 Score=0.6526
  Avg TP=12.4, TN=14.4, FP=5.6, FN=7.6
  Avg PCA Components Used: 11.0
SVM (Linear):
  Accuracy=0.7050, Precision=0.7567, Recall=0.7100, F1 Score=0.6982
  Avg TP=14.2, TN=14.0, FP=6.0, FN=5.8
  Avg PCA Components Used: 11.0
XGBoost:
  Accuracy=0.6450, Precision=0.7375, Recall=0.5300, F1 Score=0.5830
  Avg TP=10.6, TN=15.2, FP=4.8, FN=9.4
  Avg PCA Components Used: 11.0

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 19 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:48] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.9000, Precision=1.0000, Recall=0.8000, F1=0.8889
        TP=16, TN=20, FP=0, FN=4
SVM (Linear): Accuracy=0.8750, Precision=0.8947, Recall=0.8500, F1=0.8718
        TP=17, TN=18, FP=2, FN=3
XGBoost: Accuracy=0.8000, Precision=0.8333, Recall=0.7500, F1=0.7895
        TP=15, TN=17, FP=3, FN=5

===== Fold 2 =====
  -> Components to reach 98% variance: 19 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:48] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5750, Precision=0.6154, Recall=0.4000, F1=0.4848
        TP=8, TN=15, FP=5, FN=12
SVM (Linear): Accuracy=0.8000, Precision=0.9286, Recall=0.6500, F1=0.7647
        TP=13, TN=19, FP=1, FN=7
XGBoost: Accuracy=0.7250, Precision=0.7368, Recall=0.7000, F1=0.7179
        TP=14, TN=15, FP=5, FN=6

===== Fold 3 =====
  -> Components to reach 98% variance: 20 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:48] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5500, Precision=0.5556, Recall=0.5000, F1=0.5263
        TP=10, TN=12, FP=8, FN=10
SVM (Linear): Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:49] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.5000, Precision=0.5000, Recall=0.5000, F1=0.5000
        TP=10, TN=10, FP=10, FN=10

===== Fold 4 =====
  -> Components to reach 98% variance: 19 components
RandomForest: Accuracy=0.6750, Precision=0.8182, Recall=0.4500, F1=0.5806
        TP=9, TN=18, FP=2, FN=11
SVM (Linear): Accuracy=0.5250, Precision=0.5556, Recall=0.2500, F1=0.3448
        TP=5, TN=16, FP=4, FN=15

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:50] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.6000, Precision=0.6667, Recall=0.4000, F1=0.5000
        TP=8, TN=16, FP=4, FN=12

===== Fold 5 =====
  -> Components to reach 98% variance: 18 components
RandomForest: Accuracy=0.5750, Precision=0.5556, Recall=0.7500, F1=0.6383
        TP=15, TN=8, FP=12, FN=5
SVM (Linear): Accuracy=0.6250, Precision=0.5806, Recall=0.9000, F1=0.7059
        TP=18, TN=7, FP=13, FN=2

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:52] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.7000, Precision=0.6429, Recall=0.9000, F1=0.7500
        TP=18, TN=10, FP=10, FN=2

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.6550, Precision=0.7089, Recall=0.5800, F1 Score=0.6238
  Avg TP=11.6, TN=14.6, FP=5.4, FN=8.4
  Avg PCA Components Used: 19.0
SVM (Linear):
  Accuracy=0.6700, Precision=0.6967, Recall=0.6400, F1 Score=0.6448
  Avg TP=12.8, TN=14.0, FP=6.0, FN=7.2
  Avg PCA Components Used: 19.0
XGBoost:
  Accuracy=0.6650, Precision=0.6759, Recall=0.6500, F1 Score=0.6515
  Avg TP=13.0, TN=13.6, FP=6.4, FN=7.0
  Avg PCA Components Used: 19.0

In [ ]:
print("\n### K-Fold + PCA - full (ทั้งตาราง) ###")
run_kfold_with_pca(full)

### K-Fold + PCA - full (ทั้งตาราง) ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 11 components
RandomForest: Accuracy=0.8625, Precision=1.0000, Recall=0.7250, F1=0.8406
        TP=29, TN=40, FP=0, FN=11
SVM (Linear): Accuracy=0.9375, Precision=0.8889, Recall=1.0000, F1=0.9412
        TP=40, TN=35, FP=5, FN=0
XGBoost: Accuracy=0.7625, Precision=0.8889, Recall=0.6000, F1=0.7164
        TP=24, TN=37, FP=3, FN=16

===== Fold 2 =====
  -> Components to reach 95% variance: 12 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:53] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.6375, Precision=0.7037, Recall=0.4750, F1=0.5672
        TP=19, TN=32, FP=8, FN=21
SVM (Linear): Accuracy=0.5250, Precision=0.5250, Recall=0.5250, F1=0.5250
        TP=21, TN=21, FP=19, FN=19
XGBoost: Accuracy=0.6625, Precision=0.7407, Recall=0.5000, F1=0.5970
        TP=20, TN=33, FP=7, FN=20

===== Fold 3 =====
  -> Components to reach 95% variance: 13 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:53] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.5000, F1=0.5000
        TP=20, TN=20, FP=20, FN=20
SVM (Linear): Accuracy=0.6250, Precision=0.6136, Recall=0.6750, F1=0.6429
        TP=27, TN=23, FP=17, FN=13
XGBoost: Accuracy=0.4375, Precision=0.4286, Recall=0.3750, F1=0.4000
        TP=15, TN=20, FP=20, FN=25

===== Fold 4 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:54] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 95% variance: 11 components
RandomForest: Accuracy=0.5625, Precision=0.6923, Recall=0.2250, F1=0.3396
        TP=9, TN=36, FP=4, FN=31
SVM (Linear): Accuracy=0.6250, Precision=0.8125, Recall=0.3250, F1=0.4643
        TP=13, TN=37, FP=3, FN=27
XGBoost: Accuracy=0.6375, Precision=0.7391, Recall=0.4250, F1=0.5397
        TP=17, TN=34, FP=6, FN=23

===== Fold 5 =====
  -> Components to reach 95% variance: 11 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:54] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.5875, Precision=0.5714, Recall=0.7000, F1=0.6292
        TP=28, TN=19, FP=21, FN=12
SVM (Linear): Accuracy=0.5750, Precision=0.5484, Recall=0.8500, F1=0.6667
        TP=34, TN=12, FP=28, FN=6
XGBoost: Accuracy=0.5875, Precision=0.5686, Recall=0.7250, F1=0.6374
        TP=29, TN=18, FP=22, FN=11

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.6300, Precision=0.6935, Recall=0.5250, F1 Score=0.5753
  Avg TP=21.0, TN=29.4, FP=10.6, FN=19.0
  Avg PCA Components Used: 11.6
SVM (Linear):
  Accuracy=0.6575, Precision=0.6777, Recall=0.6750, F1 Score=0.6480
  Avg TP=27.0, TN=25.6, FP=14.4, FN=13.0
  Avg PCA Components Used: 11.6
XGBoost:
  Accuracy=0.6175, Precision=0.6732, Recall=0.5250, F1 Score=0.5781
  Avg TP=21.0, TN=28.4, FP=11.6, FN=19.0
  Avg PCA Components Used: 11.6

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 20 components

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:54] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

RandomForest: Accuracy=0.8500, Precision=0.9667, Recall=0.7250, F1=0.8286
        TP=29, TN=39, FP=1, FN=11
SVM (Linear): Accuracy=0.7750, Precision=0.7895, Recall=0.7500, F1=0.7692
        TP=30, TN=32, FP=8, FN=10
XGBoost: Accuracy=0.7625, Precision=0.8000, Recall=0.7000, F1=0.7467
        TP=28, TN=33, FP=7, FN=12

===== Fold 2 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:55] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 98% variance: 21 components
RandomForest: Accuracy=0.5875, Precision=0.6400, Recall=0.4000, F1=0.4923
        TP=16, TN=31, FP=9, FN=24
SVM (Linear): Accuracy=0.6125, Precision=0.6452, Recall=0.5000, F1=0.5634
        TP=20, TN=29, FP=11, FN=20
XGBoost: Accuracy=0.6125, Precision=0.6552, Recall=0.4750, F1=0.5507
        TP=19, TN=30, FP=10, FN=21

===== Fold 3 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:55] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 98% variance: 22 components
RandomForest: Accuracy=0.5750, Precision=0.5625, Recall=0.6750, F1=0.6136
        TP=27, TN=19, FP=21, FN=13
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.7500, F1=0.6000
        TP=30, TN=10, FP=30, FN=10
XGBoost: Accuracy=0.4625, Precision=0.4595, Recall=0.4250, F1=0.4416
        TP=17, TN=20, FP=20, FN=23

===== Fold 4 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:56] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 98% variance: 21 components
RandomForest: Accuracy=0.5625, Precision=0.5676, Recall=0.5250, F1=0.5455
        TP=21, TN=24, FP=16, FN=19
SVM (Linear): Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=22, TN=30, FP=10, FN=18
XGBoost: Accuracy=0.6625, Precision=0.6970, Recall=0.5750, F1=0.6301
        TP=23, TN=30, FP=10, FN=17

===== Fold 5 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:56] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

  -> Components to reach 98% variance: 20 components
RandomForest: Accuracy=0.5875, Precision=0.5778, Recall=0.6500, F1=0.6118
        TP=26, TN=21, FP=19, FN=14
SVM (Linear): Accuracy=0.3750, Precision=0.3529, Recall=0.3000, F1=0.3243
        TP=12, TN=18, FP=22, FN=28
XGBoost: Accuracy=0.5375, Precision=0.5306, Recall=0.6500, F1=0.5843
        TP=26, TN=17, FP=23, FN=14

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.6325, Precision=0.6629, Recall=0.5950, F1 Score=0.6183
  Avg TP=23.8, TN=26.8, FP=13.2, FN=16.2
  Avg PCA Components Used: 20.8
SVM (Linear):
  Accuracy=0.5825, Precision=0.5950, Recall=0.5700, F1 Score=0.5736
  Avg TP=22.8, TN=23.8, FP=16.2, FN=17.2
  Avg PCA Components Used: 20.8
XGBoost:
  Accuracy=0.6075, Precision=0.6284, Recall=0.5650, F1 Score=0.5907
  Avg TP=22.6, TN=26.0, FP=14.0, FN=17.4
  Avg PCA Components Used: 20.8

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:35:57] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)