<a href="https://colab.research.google.com/github/sitthatkaja/ParkinsonAIModel/blob/main/%5BClassification%5D_Non_NormalFA_Frame_skip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Classification] Non NormalFA Frame skip

This colab is a code for Classification (Parkinson or not) for ``` Frame skip in 3 Facial Action Scenario following: Non-Smile, Smile, and Combine``` introducing methodology.

***Note: if you have any problem please check in my github: https://github.com/sitthatkaja/ParkinsonAIModel***

---

## 1. Data Input
---

This section you need to input data form data collect in github. This setep is depend on user. You can use  ``` Google sheet link with google Drive ``` to import Data.

***Note: This section is not to shown because a privacy of account.***

## 2. Data Preprocessing
---

Form my input this is sliding video to half for  `3 Facial Action Scenarios following: Non-Smile, Smile, and Combine` that is mean the data should be counting of half it (53175 Columns in Frame skip)


***note: This method have something wrong or error of colab including: number of column. you can ignore it.***

In [ ]:
for i in range(1, len(dfs) + 1):
    globals()[f'df{i}'] = dfs[f'df{i}']

In [ ]:
dfss = [globals()[f'df{i}'] for i in range(1, len(dfs) + 1)]

In [ ]:
for i in range(len(dfss)):
    dfss[i] = dfss[i].iloc[:, 5:]

In [ ]:
dfss_odd = []
dfss_even = []
dfss_combined = []

for i in range(len(dfss)):
    df = dfss[i]

    # แยกแถวคี่และคู่ในแต่ละ DataFrame
    odd_rows = df.iloc[1::2]  # เลือกแถวคี่ (index เริ่มที่ 1, ข้ามทีละ 2)
    even_rows = df.iloc[0::2]  # เลือกแถวคู่ (index เริ่มที่ 0, ข้ามทีละ 2)

    # รวมแถวคี่ทั้งหมดเป็น 1 row
    flattened_odd = pd.concat([odd_rows.iloc[j] for j in range(len(odd_rows))]).reset_index(drop=True)

    # รวมแถวคู่ทั้งหมดเป็น 1 row
    flattened_even = pd.concat([even_rows.iloc[j] for j in range(len(even_rows))]).reset_index(drop=True)

    flattened_odd = flattened_odd.iloc[:106350]
    flattened_even = flattened_even.iloc[:106350]

    combined_row = pd.concat([flattened_even, flattened_odd], axis=1).reset_index(drop=True)

    # แปลงกลับเป็น DataFrame ที่มี 1 แถว
    dfss_odd.append(pd.DataFrame([flattened_odd]))
    dfss_even.append(pd.DataFrame([flattened_even]))
    dfss_combined.append(pd.DataFrame([combined_row.values.flatten()]))

In [ ]:
combined_df = pd.concat(dfss_even, axis=0).reset_index(drop=True) #เลือกแค่ even รันเฟมที่ 1,3,5 ไปเรื่อยๆ

In [ ]:
full = combined_df.iloc[:,:53175]
full

,0,1,2,3,4,5,6,7,8,9,...,52456,52457,52458,52459,52460,52461,52462,52463,52464,52465
0,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,0.206,434.9,440.2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.165000,0.281527,-0.945261,-0.105064,0.266013,-0.958227,0.031,0.280,396.0,402.2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.141283,0.305359,-0.941698,-0.102089,0.303798,-0.947251,0.021,0.312,469.2,475.6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,0.109993,0.249438,-0.962124,-0.185233,0.327856,-0.926390,-0.040,0.297,369.4,372.8,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,0.207585,0.273623,-0.939169,-0.065616,0.329009,-0.942044,0.075,0.310,376.9,382.3,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.017815,0.229241,-0.973207,-0.063155,0.209498,-0.975767,-0.023,0.221,461.5,466.9,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
396,0.030628,0.194938,-0.980337,-0.067250,0.160477,-0.984746,-0.019,0.179,484.6,490.4,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
397,0.022909,0.186868,-0.982118,-0.039888,0.170034,-0.984631,-0.009,0.180,476.9,482.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
398,0.029517,0.219635,-0.975135,-0.054893,0.164015,-0.984929,-0.013,0.193,460.9,466.1,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
399,0.037639,0.247780,-0.968085,-0.038300,0.204927,-0.978028,-0.000,0.229,471.2,476.6,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
full.isnull().values.any()

np.False_

## 3. Modeling
---
This section is Modeling when you prepare data form data preprocessing. This method, You should to try setup form other side and coding following: PCA and 3 Models.

***Note: This section in for experimental for all. It's means some value is non-using for report.***

3.1 NO PCA

In [ ]:
status = df[['Paror1Healthy0', 'kfold','ForS']]
status

     Paror1Healthy0  kfold  ForS
0                 1      1     1
1                 1      1     1
2                 1      1     1
3                 1      1     1
4                 1      1     1
..              ...    ...   ...
395               0      5     2
396               0      5     2
397               0      5     2
398               0      5     2
399               0      5     2

[400 rows x 3 columns]

In [ ]:
full = pd.concat([status,full], axis=1)
full

,Paror1Healthy0,kfold,ForS,0,1,2,3,4,5,6,...,52456,52457,52458,52459,52460,52461,52462,52463,52464,52465
0,1,1,1,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,1,1,1,0.165000,0.281527,-0.945261,-0.105064,0.266013,-0.958227,0.031,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1,1,1,0.141283,0.305359,-0.941698,-0.102089,0.303798,-0.947251,0.021,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,1,1,1,0.109993,0.249438,-0.962124,-0.185233,0.327856,-0.926390,-0.040,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,1,1,1,0.207585,0.273623,-0.939169,-0.065616,0.329009,-0.942044,0.075,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,5,2,0.017815,0.229241,-0.973207,-0.063155,0.209498,-0.975767,-0.023,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
396,0,5,2,0.030628,0.194938,-0.980337,-0.067250,0.160477,-0.984746,-0.019,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
397,0,5,2,0.022909,0.186868,-0.982118,-0.039888,0.170034,-0.984631,-0.009,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
398,0,5,2,0.029517,0.219635,-0.975135,-0.054893,0.164015,-0.984929,-0.013,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
399,0,5,2,0.037639,0.247780,-0.968085,-0.038300,0.204927,-0.978028,-0.000,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
# แยก full ตาม ForS
full_first = full[full['ForS'] == 1].reset_index(drop=True)
full_second = full[full['ForS'] == 2].reset_index(drop=True)
# full เดิมคือทั้งครึ่งแรกและครึ่งหลัง

In [ ]:
def run_kfold_no_pca(df, target_col='Paror1Healthy0', kfold_col='kfold'):
    models = {
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel="linear")
    }

    results = {name: {
        "accuracy": [], "precision": [], "recall": [], "f1": [],
        "TP": [], "TN": [], "FP": [], "FN": []
    } for name in models}

    for fold in range(1, 6):
        print(f"\n===== Fold {fold} =====")
        df_train = df[df[kfold_col] != fold].reset_index(drop=True)
        df_valid = df[df[kfold_col] == fold].reset_index(drop=True)

        # ดรอป target, kfold, ForS (ถ้ามี) ออกจาก X
        drop_cols = [target_col, kfold_col]
        if 'ForS' in df.columns:
            drop_cols.append('ForS')

        X_train = df_train.drop(columns=drop_cols)
        y_train = df_train[target_col]
        X_valid = df_valid.drop(columns=drop_cols)
        y_valid = df_valid[target_col]

        for name, model in models.items():
            model.fit(X_train, y_train)
            preds = model.predict(X_valid)

            accuracy = accuracy_score(y_valid, preds)
            precision = precision_score(y_valid, preds, average='binary')
            recall = recall_score(y_valid, preds, average='binary')
            f1 = f1_score(y_valid, preds, average='binary')
            tn, fp, fn, tp = confusion_matrix(y_valid, preds).ravel()

            results[name]["accuracy"].append(accuracy)
            results[name]["precision"].append(precision)
            results[name]["recall"].append(recall)
            results[name]["f1"].append(f1)
            results[name]["TP"].append(tp)
            results[name]["TN"].append(tn)
            results[name]["FP"].append(fp)
            results[name]["FN"].append(fn)

            print(f"{name}: Accuracy={accuracy:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
            print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

    # สรุปค่าเฉลี่ยแต่ละโมเดล
    print("\n===== Average Performance Across 5 Folds =====")
    for name in models:
        avg_acc = sum(results[name]["accuracy"]) / 5
        avg_prec = sum(results[name]["precision"]) / 5
        avg_rec = sum(results[name]["recall"]) / 5
        avg_f1 = sum(results[name]["f1"]) / 5
        avg_tp = sum(results[name]["TP"]) / 5
        avg_tn = sum(results[name]["TN"]) / 5
        avg_fp = sum(results[name]["FP"]) / 5
        avg_fn = sum(results[name]["FN"]) / 5

        print(f"{name}:")
        print(f"  Accuracy={avg_acc:.4f}, Precision={avg_prec:.4f}, Recall={avg_rec:.4f}, F1 Score={avg_f1:.4f}")
        print(f"  Avg TP={avg_tp:.1f}, TN={avg_tn:.1f}, FP={avg_fp:.1f}, FN={avg_fn:.1f}")

In [ ]:
print("\n### K-Fold (No PCA) - full_first ###")
run_kfold_no_pca(full_first)

### K-Fold (No PCA) - full_first ###

===== Fold 1 =====
RandomForest: Accuracy=0.8250, Precision=1.0000, Recall=0.6500, F1=0.7879
        TP=13, TN=20, FP=0, FN=7
SVM: Accuracy=0.6000, Precision=0.6667, Recall=0.4000, F1=0.5000
        TP=8, TN=16, FP=4, FN=12

===== Fold 2 =====
RandomForest: Accuracy=0.7750, Precision=0.7391, Recall=0.8500, F1=0.7907
        TP=17, TN=14, FP=6, FN=3
SVM: Accuracy=0.5500, Precision=0.5556, Recall=0.5000, F1=0.5263
        TP=10, TN=12, FP=8, FN=10

===== Fold 3 =====
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.7000, F1=0.5833
        TP=14, TN=6, FP=14, FN=6
SVM: Accuracy=0.2500, Precision=0.3077, Recall=0.4000, F1=0.3478
        TP=8, TN=2, FP=18, FN=12

===== Fold 4 =====
RandomForest: Accuracy=0.6000, Precision=0.6667, Recall=0.4000, F1=0.5000
        TP=8, TN=16, FP=4, FN=12
SVM: Accuracy=0.5750, Precision=0.7143, Recall=0.2500, F1=0.3704
        TP=5, TN=18, FP=2, FN=15

===== Fold 5 =====
RandomForest: Accuracy=0.4500, Precision=0.4167, Recall=0.2500, F1=0.3125
        TP=5, TN=13, FP=7, FN=15
SVM: Accuracy=0.4250, Precision=0.4000, Recall=0.3000, F1=0.3429
        TP=6, TN=11, FP=9, FN=14

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6300, Precision=0.6645, Recall=0.5700, F1 Score=0.5949
  Avg TP=11.4, TN=13.8, FP=6.2, FN=8.6
SVM:
  Accuracy=0.4800, Precision=0.5288, Recall=0.3700, F1 Score=0.4175
  Avg TP=7.4, TN=11.8, FP=8.2, FN=12.6

In [ ]:
print("\n### K-Fold (No PCA) - full_second ###")
run_kfold_no_pca(full_second)

### K-Fold (No PCA) - full_second ###

===== Fold 1 =====
RandomForest: Accuracy=0.9500, Precision=0.9091, Recall=1.0000, F1=0.9524
        TP=20, TN=18, FP=2, FN=0
SVM: Accuracy=0.8500, Precision=0.9375, Recall=0.7500, F1=0.8333
        TP=15, TN=19, FP=1, FN=5

===== Fold 2 =====
RandomForest: Accuracy=0.8000, Precision=0.7727, Recall=0.8500, F1=0.8095
        TP=17, TN=15, FP=5, FN=3
SVM: Accuracy=0.7000, Precision=0.7500, Recall=0.6000, F1=0.6667
        TP=12, TN=16, FP=4, FN=8

===== Fold 3 =====
RandomForest: Accuracy=0.5500, Precision=0.5357, Recall=0.7500, F1=0.6250
        TP=15, TN=7, FP=13, FN=5
SVM: Accuracy=0.1750, Precision=0.2174, Recall=0.2500, F1=0.2326
        TP=5, TN=2, FP=18, FN=15

===== Fold 4 =====
RandomForest: Accuracy=0.5750, Precision=0.6154, Recall=0.4000, F1=0.4848
        TP=8, TN=15, FP=5, FN=12
SVM: Accuracy=0.6000, Precision=0.8333, Recall=0.2500, F1=0.3846
        TP=5, TN=19, FP=1, FN=15

===== Fold 5 =====
RandomForest: Accuracy=0.4500, Precision=0.4286, Recall=0.3000, F1=0.3529
        TP=6, TN=12, FP=8, FN=14
SVM: Accuracy=0.4250, Precision=0.4211, Recall=0.4000, F1=0.4103
        TP=8, TN=9, FP=11, FN=12

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6650, Precision=0.6523, Recall=0.6600, F1 Score=0.6449
  Avg TP=13.2, TN=13.4, FP=6.6, FN=6.8
SVM:
  Accuracy=0.5500, Precision=0.6319, Recall=0.4500, F1 Score=0.5055
  Avg TP=9.0, TN=13.0, FP=7.0, FN=11.0

In [ ]:
print("\n### K-Fold (No PCA) - full (ทั้งตาราง) ###")
run_kfold_no_pca(full)

### K-Fold (No PCA) - full (ทั้งตาราง) ###

===== Fold 1 =====
RandomForest: Accuracy=0.8250, Precision=1.0000, Recall=0.6500, F1=0.7879
        TP=26, TN=40, FP=0, FN=14
SVM: Accuracy=0.7875, Precision=0.8485, Recall=0.7000, F1=0.7671
        TP=28, TN=35, FP=5, FN=12

===== Fold 2 =====
RandomForest: Accuracy=0.7125, Precision=0.7179, Recall=0.7000, F1=0.7089
        TP=28, TN=29, FP=11, FN=12
SVM: Accuracy=0.5750, Precision=0.6000, Recall=0.4500, F1=0.5143
        TP=18, TN=28, FP=12, FN=22

===== Fold 3 =====
RandomForest: Accuracy=0.5125, Precision=0.5085, Recall=0.7500, F1=0.6061
        TP=30, TN=11, FP=29, FN=10
SVM: Accuracy=0.2875, Precision=0.3455, Recall=0.4750, F1=0.4000
        TP=19, TN=4, FP=36, FN=21

===== Fold 4 =====
RandomForest: Accuracy=0.6625, Precision=0.6970, Recall=0.5750, F1=0.6301
        TP=23, TN=30, FP=10, FN=17
SVM: Accuracy=0.5625, Precision=0.6471, Recall=0.2750, F1=0.3860
        TP=11, TN=34, FP=6, FN=29

===== Fold 5 =====
RandomForest: Accuracy=0.3875, Precision=0.3448, Recall=0.2500, F1=0.2899
        TP=10, TN=21, FP=19, FN=30
SVM: Accuracy=0.3625, Precision=0.3226, Recall=0.2500, F1=0.2817
        TP=10, TN=19, FP=21, FN=30

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6200, Precision=0.6536, Recall=0.5850, F1 Score=0.6046
  Avg TP=23.4, TN=26.2, FP=13.8, FN=16.6
SVM:
  Accuracy=0.5150, Precision=0.5527, Recall=0.4300, F1 Score=0.4698
  Avg TP=17.2, TN=24.0, FP=16.0, FN=22.8

---
#### 3.2 PCA 95% and 98% variance

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import numpy as np

def run_kfold_with_pca(df, target_col='Paror1Healthy0', kfold_col='kfold', variances=[0.95, 0.98]):
    models = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
        "SVM (Linear)": SVC(kernel='linear'),
    }

    for var in variances:
        print(f"\n===== PCA with Explained Variance = {var} =====")
        results = {name: [] for name in models.keys()}

        for fold in range(1, 6):
            print(f"\n===== Fold {fold} =====")
            train_df = df[df[kfold_col] != fold].reset_index(drop=True)
            valid_df = df[df[kfold_col] == fold].reset_index(drop=True)

            drop_cols = [target_col, kfold_col]
            if 'ForS' in df.columns:
                drop_cols.append('ForS')

            X_train = train_df.drop(columns=drop_cols).values
            y_train = train_df[target_col].values
            X_valid = valid_df.drop(columns=drop_cols).values
            y_valid = valid_df[target_col].values

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_valid_scaled = scaler.transform(X_valid)

            pca = PCA(n_components=var)
            X_train_pca = pca.fit_transform(X_train_scaled)
            X_valid_pca = pca.transform(X_valid_scaled)

            n_components_used = X_train_pca.shape[1]
            print(f"  -> Components to reach {var*100:.0f}% variance: {n_components_used} components")

            for name, model in models.items():
                model.fit(X_train_pca, y_train)
                y_pred = model.predict(X_valid_pca)

                acc = accuracy_score(y_valid, y_pred)
                f1 = f1_score(y_valid, y_pred)
                recall = recall_score(y_valid, y_pred)
                precision = precision_score(y_valid, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_valid, y_pred).ravel()

                results[name].append({
                    'fold': fold,
                    'n_components': n_components_used,
                    'accuracy': acc,
                    'f1_score': f1,
                    'recall': recall,
                    'precision': precision,
                    'tn': tn,
                    'fp': fp,
                    'fn': fn,
                    'tp': tp
                })

                print(f"{name}: Accuracy={acc:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
                print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

        # สรุปค่าเฉลี่ย
        print(f"\n===== Average Performance Across 5 Folds (Explained Variance = {var}) =====")
        for name in results:
            accuracies = [r['accuracy'] for r in results[name]]
            f1s = [r['f1_score'] for r in results[name]]
            recalls = [r['recall'] for r in results[name]]
            precisions = [r['precision'] for r in results[name]]
            tns = [r['tn'] for r in results[name]]
            fps = [r['fp'] for r in results[name]]
            fns = [r['fn'] for r in results[name]]
            tps = [r['tp'] for r in results[name]]
            components = [r['n_components'] for r in results[name]]

            print(f"{name}:")
            print(f"  Accuracy={np.mean(accuracies):.4f}, Precision={np.mean(precisions):.4f}, Recall={np.mean(recalls):.4f}, F1 Score={np.mean(f1s):.4f}")
            print(f"  Avg TP={np.mean(tps):.1f}, TN={np.mean(tns):.1f}, FP={np.mean(fps):.1f}, FN={np.mean(fns):.1f}")
            print(f"  Avg PCA Components Used: {np.mean(components):.1f}")

In [ ]:
print("\n### K-Fold + PCA - full_first ###")
run_kfold_with_pca(full_first)

### K-Fold + PCA - full_first ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 17 components
RandomForest: Accuracy=0.9750, Precision=0.9524, Recall=1.0000, F1=0.9756
        TP=20, TN=19, FP=1, FN=0
SVM (Linear): Accuracy=0.8000, Precision=0.8333, Recall=0.7500, F1=0.7895
        TP=15, TN=17, FP=3, FN=5

===== Fold 2 =====
  -> Components to reach 95% variance: 17 components
RandomForest: Accuracy=0.6750, Precision=0.7059, Recall=0.6000, F1=0.6486
        TP=12, TN=15, FP=5, FN=8
SVM (Linear): Accuracy=0.5250, Precision=0.5263, Recall=0.5000, F1=0.5128
        TP=10, TN=11, FP=9, FN=10

===== Fold 3 =====
  -> Components to reach 95% variance: 20 components
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.5000, F1=0.5000
        TP=10, TN=10, FP=10, FN=10
SVM (Linear): Accuracy=0.5750, Precision=0.6000, Recall=0.4500, F1=0.5143
        TP=9, TN=14, FP=6, FN=11

===== Fold 4 =====
  -> Components to reach 95% variance: 18 components
RandomForest: Accuracy=0.6750, Precision=0.8182, Recall=0.4500, F1=0.5806
        TP=9, TN=18, FP=2, FN=11
SVM (Linear): Accuracy=0.4750, Precision=0.4667, Recall=0.3500, F1=0.4000
        TP=7, TN=12, FP=8, FN=13

===== Fold 5 =====
  -> Components to reach 95% variance: 15 components
RandomForest: Accuracy=0.7250, Precision=0.6957, Recall=0.8000, F1=0.7442
        TP=16, TN=13, FP=7, FN=4
SVM (Linear): Accuracy=0.5750, Precision=0.5455, Recall=0.9000, F1=0.6792
        TP=18, TN=5, FP=15, FN=2

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.7100, Precision=0.7344, Recall=0.6700, F1 Score=0.6898
  Avg TP=13.4, TN=15.0, FP=5.0, FN=6.6
  Avg PCA Components Used: 17.4
SVM (Linear):
  Accuracy=0.5900, Precision=0.5944, Recall=0.5900, F1 Score=0.5792
  Avg TP=11.8, TN=11.8, FP=8.2, FN=8.2
  Avg PCA Components Used: 17.4

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 30 components
RandomForest: Accuracy=0.7750, Precision=0.8235, Recall=0.7000, F1=0.7568
        TP=14, TN=17, FP=3, FN=6
SVM (Linear): Accuracy=0.7000, Precision=0.6667, Recall=0.8000, F1=0.7273
        TP=16, TN=12, FP=8, FN=4

===== Fold 2 =====
  -> Components to reach 98% variance: 29 components
RandomForest: Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9
SVM (Linear): Accuracy=0.6000, Precision=0.6250, Recall=0.5000, F1=0.5556
        TP=10, TN=14, FP=6, FN=10

===== Fold 3 =====
  -> Components to reach 98% variance: 35 components
RandomForest: Accuracy=0.5500, Precision=0.5455, Recall=0.6000, F1=0.5714
        TP=12, TN=10, FP=10, FN=8
SVM (Linear): Accuracy=0.6500, Precision=0.6667, Recall=0.6000, F1=0.6316
        TP=12, TN=14, FP=6, FN=8

===== Fold 4 =====
  -> Components to reach 98% variance: 31 components
RandomForest: Accuracy=0.6000, Precision=0.6667, Recall=0.4000, F1=0.5000
        TP=8, TN=16, FP=4, FN=12
SVM (Linear): Accuracy=0.5500, Precision=0.6250, Recall=0.2500, F1=0.3571
        TP=5, TN=17, FP=3, FN=15

===== Fold 5 =====
  -> Components to reach 98% variance: 29 components
RandomForest: Accuracy=0.6000, Precision=0.5833, Recall=0.7000, F1=0.6364
        TP=14, TN=10, FP=10, FN=6
SVM (Linear): Accuracy=0.3250, Precision=0.0000, Recall=0.0000, F1=0.0000
        TP=0, TN=13, FP=7, FN=20

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.6350, Precision=0.6613, Recall=0.5900, F1 Score=0.6151
  Avg TP=11.8, TN=13.6, FP=6.4, FN=8.2
  Avg PCA Components Used: 30.8
SVM (Linear):
  Accuracy=0.5650, Precision=0.5167, Recall=0.4300, F1 Score=0.4543
  Avg TP=8.6, TN=14.0, FP=6.0, FN=11.4
  Avg PCA Components Used: 30.8

In [ ]:
print("\n### K-Fold + PCA - full_second ###")
run_kfold_with_pca(full_second)

### K-Fold + PCA - full_second ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 15 components
RandomForest: Accuracy=0.9500, Precision=1.0000, Recall=0.9000, F1=0.9474
        TP=18, TN=20, FP=0, FN=2
SVM (Linear): Accuracy=0.9250, Precision=0.9474, Recall=0.9000, F1=0.9231
        TP=18, TN=19, FP=1, FN=2

===== Fold 2 =====
  -> Components to reach 95% variance: 15 components
RandomForest: Accuracy=0.6250, Precision=0.6316, Recall=0.6000, F1=0.6154
        TP=12, TN=13, FP=7, FN=8
SVM (Linear): Accuracy=0.6500, Precision=0.8000, Recall=0.4000, F1=0.5333
        TP=8, TN=18, FP=2, FN=12

===== Fold 3 =====
  -> Components to reach 95% variance: 19 components
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.7500, F1=0.6000
        TP=15, TN=5, FP=15, FN=5
SVM (Linear): Accuracy=0.7500, Precision=0.7500, Recall=0.7500, F1=0.7500
        TP=15, TN=15, FP=5, FN=5

===== Fold 4 =====
  -> Components to reach 95% variance: 15 components
RandomForest: Accuracy=0.7750, Precision=0.7619, Recall=0.8000, F1=0.7805
        TP=16, TN=15, FP=5, FN=4
SVM (Linear): Accuracy=0.7250, Precision=0.7368, Recall=0.7000, F1=0.7179
        TP=14, TN=15, FP=5, FN=6

===== Fold 5 =====
  -> Components to reach 95% variance: 16 components
RandomForest: Accuracy=0.7750, Precision=0.6897, Recall=1.0000, F1=0.8163
        TP=20, TN=11, FP=9, FN=0
SVM (Linear): Accuracy=0.6250, Precision=0.5714, Recall=1.0000, F1=0.7273
        TP=20, TN=5, FP=15, FN=0

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.7250, Precision=0.7166, Recall=0.8100, F1 Score=0.7519
  Avg TP=16.2, TN=12.8, FP=7.2, FN=3.8
  Avg PCA Components Used: 16.0
SVM (Linear):
  Accuracy=0.7350, Precision=0.7611, Recall=0.7500, F1 Score=0.7303
  Avg TP=15.0, TN=14.4, FP=5.6, FN=5.0
  Avg PCA Components Used: 16.0

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 29 components
RandomForest: Accuracy=0.9250, Precision=0.8696, Recall=1.0000, F1=0.9302
        TP=20, TN=17, FP=3, FN=0
SVM (Linear): Accuracy=0.7000, Precision=0.6429, Recall=0.9000, F1=0.7500
        TP=18, TN=10, FP=10, FN=2

===== Fold 2 =====
  -> Components to reach 98% variance: 27 components
RandomForest: Accuracy=0.6750, Precision=0.6842, Recall=0.6500, F1=0.6667
        TP=13, TN=14, FP=6, FN=7
SVM (Linear): Accuracy=0.7500, Precision=0.9167, Recall=0.5500, F1=0.6875
        TP=11, TN=19, FP=1, FN=9

===== Fold 3 =====
  -> Components to reach 98% variance: 34 components
RandomForest: Accuracy=0.4750, Precision=0.4828, Recall=0.7000, F1=0.5714
        TP=14, TN=5, FP=15, FN=6
SVM (Linear): Accuracy=0.6250, Precision=0.6087, Recall=0.7000, F1=0.6512
        TP=14, TN=11, FP=9, FN=6

===== Fold 4 =====
  -> Components to reach 98% variance: 29 components
RandomForest: Accuracy=0.7500, Precision=0.7500, Recall=0.7500, F1=0.7500
        TP=15, TN=15, FP=5, FN=5
SVM (Linear): Accuracy=0.5250, Precision=0.5556, Recall=0.2500, F1=0.3448
        TP=5, TN=16, FP=4, FN=15

===== Fold 5 =====
  -> Components to reach 98% variance: 30 components
RandomForest: Accuracy=0.9000, Precision=0.8333, Recall=1.0000, F1=0.9091
        TP=20, TN=16, FP=4, FN=0
SVM (Linear): Accuracy=0.6000, Precision=0.5769, Recall=0.7500, F1=0.6522
        TP=15, TN=9, FP=11, FN=5

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.7450, Precision=0.7240, Recall=0.8200, F1 Score=0.7655
  Avg TP=16.4, TN=13.4, FP=6.6, FN=3.6
  Avg PCA Components Used: 29.8
SVM (Linear):
  Accuracy=0.6400, Precision=0.6601, Recall=0.6300, F1 Score=0.6171
  Avg TP=12.6, TN=13.0, FP=7.0, FN=7.4
  Avg PCA Components Used: 29.8

In [ ]:
print("\n### K-Fold + PCA - full (ทั้งตาราง) ###")
run_kfold_with_pca(full)

### K-Fold + PCA - full (ทั้งตาราง) ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 19 components
RandomForest: Accuracy=0.8250, Precision=0.9333, Recall=0.7000, F1=0.8000
        TP=28, TN=38, FP=2, FN=12
SVM (Linear): Accuracy=0.8250, Precision=0.8611, Recall=0.7750, F1=0.8158
        TP=31, TN=35, FP=5, FN=9

===== Fold 2 =====
  -> Components to reach 95% variance: 19 components
RandomForest: Accuracy=0.6625, Precision=0.7241, Recall=0.5250, F1=0.6087
        TP=21, TN=32, FP=8, FN=19
SVM (Linear): Accuracy=0.5750, Precision=0.6071, Recall=0.4250, F1=0.5000
        TP=17, TN=29, FP=11, FN=23

===== Fold 3 =====
  -> Components to reach 95% variance: 25 components
RandomForest: Accuracy=0.2750, Precision=0.2750, Recall=0.2750, F1=0.2750
        TP=11, TN=11, FP=29, FN=29
SVM (Linear): Accuracy=0.5875, Precision=0.5714, Recall=0.7000, F1=0.6292
        TP=28, TN=19, FP=21, FN=12

===== Fold 4 =====
  -> Components to reach 95% variance: 20 components
RandomForest: Accuracy=0.7250, Precision=0.7647, Recall=0.6500, F1=0.7027
        TP=26, TN=32, FP=8, FN=14
SVM (Linear): Accuracy=0.6375, Precision=0.7037, Recall=0.4750, F1=0.5672
        TP=19, TN=32, FP=8, FN=21

===== Fold 5 =====
  -> Components to reach 95% variance: 18 components
RandomForest: Accuracy=0.7000, Precision=0.6667, Recall=0.8000, F1=0.7273
        TP=32, TN=24, FP=16, FN=8
SVM (Linear): Accuracy=0.5375, Precision=0.5246, Recall=0.8000, F1=0.6337
        TP=32, TN=11, FP=29, FN=8

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.6375, Precision=0.6728, Recall=0.5900, F1 Score=0.6227
  Avg TP=23.6, TN=27.4, FP=12.6, FN=16.4
  Avg PCA Components Used: 20.2
SVM (Linear):
  Accuracy=0.6325, Precision=0.6536, Recall=0.6350, F1 Score=0.6292
  Avg TP=25.4, TN=25.2, FP=14.8, FN=14.6
  Avg PCA Components Used: 20.2

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 37 components
RandomForest: Accuracy=0.6500, Precision=0.7500, Recall=0.4500, F1=0.5625
        TP=18, TN=34, FP=6, FN=22
SVM (Linear): Accuracy=0.6375, Precision=0.6078, Recall=0.7750, F1=0.6813
        TP=31, TN=20, FP=20, FN=9

===== Fold 2 =====
  -> Components to reach 98% variance: 35 components
RandomForest: Accuracy=0.6750, Precision=0.7059, Recall=0.6000, F1=0.6486
        TP=24, TN=30, FP=10, FN=16
SVM (Linear): Accuracy=0.6125, Precision=0.6452, Recall=0.5000, F1=0.5634
        TP=20, TN=29, FP=11, FN=20

===== Fold 3 =====
  -> Components to reach 98% variance: 46 components
RandomForest: Accuracy=0.3375, Precision=0.3556, Recall=0.4000, F1=0.3765
        TP=16, TN=11, FP=29, FN=24
SVM (Linear): Accuracy=0.5625, Precision=0.5490, Recall=0.7000, F1=0.6154
        TP=28, TN=17, FP=23, FN=12

===== Fold 4 =====
  -> Components to reach 98% variance: 39 components
RandomForest: Accuracy=0.6375, Precision=0.6897, Recall=0.5000, F1=0.5797
        TP=20, TN=31, FP=9, FN=20
SVM (Linear): Accuracy=0.4875, Precision=0.4762, Recall=0.2500, F1=0.3279
        TP=10, TN=29, FP=11, FN=30

===== Fold 5 =====
  -> Components to reach 98% variance: 37 components
RandomForest: Accuracy=0.6250, Precision=0.6190, Recall=0.6500, F1=0.6341
        TP=26, TN=24, FP=16, FN=14
SVM (Linear): Accuracy=0.3250, Precision=0.1818, Recall=0.1000, F1=0.1290
        TP=4, TN=22, FP=18, FN=36

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5850, Precision=0.6240, Recall=0.5200, F1 Score=0.5603
  Avg TP=20.8, TN=26.0, FP=14.0, FN=19.2
  Avg PCA Components Used: 38.8
SVM (Linear):
  Accuracy=0.5250, Precision=0.4920, Recall=0.4650, F1 Score=0.4634
  Avg TP=18.6, TN=23.4, FP=16.6, FN=21.4
  Avg PCA Components Used: 38.8