<a href="https://colab.research.google.com/github/sitthatkaja/ParkinsonAIModel/blob/main/%5BClassification%5D_Non_NormalFA_frame_difference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Classification] Non NormalFA frame difference

This colab is a code for Classification (Parkinson or not) for ``` frame difference in 3 Facial Action Scenario following: Non-Smile, Smile, and Combine``` introducing methodology.

***Note: if you have any problem please check in my github: https://github.com/sitthatkaja/ParkinsonAIModel***

---

## 1. Data Input
---

This section you need to input data form data collect in github. This setep is depend on user. You can use  ``` Google sheet link with google Drive ``` to import Data.

***Note: This section is not to shown because a privacy of account.***

## 2. Data Preprocessing
---

Form my input this is sliding video to half for  `3 Facial Action Scenarios following: Non-Smile, Smile, and Combine` that is mean the data should be counting of half it (105641 Columns in frame difference)


***note: This method have something wrong or error of colab including: number of column. you can ignore it.***

In [ ]:
for i in range(1, len(dfs) + 1):
    globals()[f'df{i}'] = dfs[f'df{i}']

In [ ]:
dfss = [globals()[f'df{i}'] for i in range(1, len(dfs) + 1)]

In [ ]:

for i in range(len(dfss)):
    dfss[i] = dfss[i].iloc[:, 5:]

In [ ]:
diff_results = []
for df in dfss:
    diff_result = df.diff().iloc[1:]  # คำนวณผลต่างแล้วข้ามแถวแรกที่เป็น NaN
    diff_results.append(diff_result)

In [ ]:
diff_results[1]

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,eye_lmk_x_0,eye_lmk_x_1,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
1,0.029944,-0.048090,-0.007369,-0.005116,-0.014563,-0.003352,0.013,-0.032,-1.3,-1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.018613,0.010742,-0.000934,-0.010103,-0.007674,-0.000765,-0.015,0.001,-2.3,-2.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.015176,-0.007911,0.000935,0.001537,0.010870,0.002628,0.009,0.002,1.7,1.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.001152,0.006317,0.001821,-0.002359,-0.000436,0.000179,-0.001,0.003,0.5,0.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,-0.004535,0.005145,0.000419,-0.003646,0.000555,0.000615,-0.004,0.003,-0.3,-0.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0.005703,0.000077,0.001223,0.006716,0.005408,0.000582,0.006,0.002,-1.1,-0.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,-0.011437,0.001593,-0.002031,-0.003527,-0.004061,-0.000596,-0.007,-0.001,0.4,0.3,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.003870,-0.010969,-0.001582,-0.007902,-0.006165,-0.000577,-0.003,-0.009,-0.2,0.4,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
148,-0.000537,0.007604,0.001520,0.005935,0.010207,0.001709,0.003,0.009,0.4,-0.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,-0.003326,0.004092,0.000225,-0.001477,0.007365,0.001901,-0.002,0.006,2.9,2.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
for i in range(len(diff_results)):
    df = diff_results[i]
    # รวมแถวทั้งหมดให้เป็น 1 row
    flattened_row = pd.concat([df.iloc[j] for j in range(len(df))]).reset_index(drop=True)

    # แปลงกลับเป็น DataFrame ที่มี 1 แถว
    diff_results[i] = pd.DataFrame([flattened_row])

In [ ]:
combined_df = pd.concat(diff_results, axis=0).reset_index(drop=True)
combined_df

,0,1,2,3,4,5,6,7,8,9,...,318331,318332,318333,318334,318335,318336,318337,318338,318339,318340
0,0.004806,0.003664,0.001541,-0.020777,0.018557,0.007895,-0.008,0.012,-3.4,-2.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.029944,-0.048090,-0.007369,-0.005116,-0.014563,-0.003352,0.013,-0.032,-1.3,-1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.052062,-0.044499,-0.004119,-0.003091,-0.020973,-0.006136,0.025,-0.033,-0.7,-1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.016307,-0.027677,-0.004763,-0.006634,0.011461,0.005493,0.005,-0.008,-4.0,-4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.006622,-0.017735,-0.003506,0.017151,-0.022173,-0.008484,0.012,-0.021,-2.6,-2.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.012995,-0.016627,-0.003443,0.014880,-0.007582,-0.002445,0.014,-0.012,0.7,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,-0.009241,-0.005281,-0.001280,-0.000725,0.003212,0.000579,-0.005,-0.001,-0.1,0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,-0.005605,-0.015759,-0.002982,0.002194,-0.036027,-0.005632,-0.001,-0.027,-0.3,-0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,-0.003083,-0.011470,-0.002601,0.002769,-0.004237,-0.000847,0.000,-0.008,0.1,0.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,-0.006893,-0.017963,-0.004663,-0.018898,-0.024203,-0.003841,-0.014,-0.022,-0.1,-0.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
full = combined_df.iloc[:,:105641]
full

,0,1,2,3,4,5,6,7,8,9,...,104213,104214,104215,104216,104217,104218,104219,104220,104221,104222
0,0.004806,0.003664,0.001541,-0.020777,0.018557,0.007895,-0.008,0.012,-3.4,-2.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.029944,-0.048090,-0.007369,-0.005116,-0.014563,-0.003352,0.013,-0.032,-1.3,-1.5,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.052062,-0.044499,-0.004119,-0.003091,-0.020973,-0.006136,0.025,-0.033,-0.7,-1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.016307,-0.027677,-0.004763,-0.006634,0.011461,0.005493,0.005,-0.008,-4.0,-4.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.006622,-0.017735,-0.003506,0.017151,-0.022173,-0.008484,0.012,-0.021,-2.6,-2.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.012995,-0.016627,-0.003443,0.014880,-0.007582,-0.002445,0.014,-0.012,0.7,0.4,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
396,-0.009241,-0.005281,-0.001280,-0.000725,0.003212,0.000579,-0.005,-0.001,-0.1,0.1,...,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0
397,-0.005605,-0.015759,-0.002982,0.002194,-0.036027,-0.005632,-0.001,-0.027,-0.3,-0.2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
398,-0.003083,-0.011470,-0.002601,0.002769,-0.004237,-0.000847,0.000,-0.008,0.1,0.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
399,-0.006893,-0.017963,-0.004663,-0.018898,-0.024203,-0.003841,-0.014,-0.022,-0.1,-0.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
full.isnull().values.any()

np.False_

## 3. Modeling
---
This section is Modeling when you prepare data form data preprocessing. This method, You should to try setup form other side and coding following: PCA and 3 Models.

***Note: This section in for experimental for all. It's means some value is non-using for report.***

3.1 NO PCA

In [ ]:
status = df[['Paror1Healthy0', 'kfold','ForS']]
status

     Paror1Healthy0  kfold  ForS
0                 1      1     1
1                 1      1     1
2                 1      1     1
3                 1      1     1
4                 1      1     1
..              ...    ...   ...
395               0      5     2
396               0      5     2
397               0      5     2
398               0      5     2
399               0      5     2

[400 rows x 3 columns]

In [ ]:
full = pd.concat([status,full], axis=1)
full

,Paror1Healthy0,kfold,ForS,0,1,2,3,4,5,6,...,104213,104214,104215,104216,104217,104218,104219,104220,104221,104222
0,1,1,1,0.004806,0.003664,0.001541,-0.020777,0.018557,0.007895,-0.008,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,1,0.029944,-0.048090,-0.007369,-0.005116,-0.014563,-0.003352,0.013,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1,1,1,0.052062,-0.044499,-0.004119,-0.003091,-0.020973,-0.006136,0.025,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,1,1,0.016307,-0.027677,-0.004763,-0.006634,0.011461,0.005493,0.005,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1,1,0.006622,-0.017735,-0.003506,0.017151,-0.022173,-0.008484,0.012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,5,2,0.012995,-0.016627,-0.003443,0.014880,-0.007582,-0.002445,0.014,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
396,0,5,2,-0.009241,-0.005281,-0.001280,-0.000725,0.003212,0.000579,-0.005,...,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0
397,0,5,2,-0.005605,-0.015759,-0.002982,0.002194,-0.036027,-0.005632,-0.001,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
398,0,5,2,-0.003083,-0.011470,-0.002601,0.002769,-0.004237,-0.000847,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
399,0,5,2,-0.006893,-0.017963,-0.004663,-0.018898,-0.024203,-0.003841,-0.014,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
# แยก full ตาม ForS
full_first = full[full['ForS'] == 1].reset_index(drop=True)
full_second = full[full['ForS'] == 2].reset_index(drop=True)
# full เดิมคือทั้งครึ่งแรกและครึ่งหลัง

In [ ]:
def run_kfold_no_pca(df, target_col='Paror1Healthy0', kfold_col='kfold'):
    models = {
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel="linear")
    }

    results = {name: {
        "accuracy": [], "precision": [], "recall": [], "f1": [],
        "TP": [], "TN": [], "FP": [], "FN": []
    } for name in models}

    for fold in range(1, 6):
        print(f"\n===== Fold {fold} =====")
        df_train = df[df[kfold_col] != fold].reset_index(drop=True)
        df_valid = df[df[kfold_col] == fold].reset_index(drop=True)

        # ดรอป target, kfold, ForS (ถ้ามี) ออกจาก X
        drop_cols = [target_col, kfold_col]
        if 'ForS' in df.columns:
            drop_cols.append('ForS')

        X_train = df_train.drop(columns=drop_cols)
        y_train = df_train[target_col]
        X_valid = df_valid.drop(columns=drop_cols)
        y_valid = df_valid[target_col]

        for name, model in models.items():
            model.fit(X_train, y_train)
            preds = model.predict(X_valid)

            accuracy = accuracy_score(y_valid, preds)
            precision = precision_score(y_valid, preds, average='binary')
            recall = recall_score(y_valid, preds, average='binary')
            f1 = f1_score(y_valid, preds, average='binary')
            tn, fp, fn, tp = confusion_matrix(y_valid, preds).ravel()

            results[name]["accuracy"].append(accuracy)
            results[name]["precision"].append(precision)
            results[name]["recall"].append(recall)
            results[name]["f1"].append(f1)
            results[name]["TP"].append(tp)
            results[name]["TN"].append(tn)
            results[name]["FP"].append(fp)
            results[name]["FN"].append(fn)

            print(f"{name}: Accuracy={accuracy:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
            print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

    # สรุปค่าเฉลี่ยแต่ละโมเดล
    print("\n===== Average Performance Across 5 Folds =====")
    for name in models:
        avg_acc = sum(results[name]["accuracy"]) / 5
        avg_prec = sum(results[name]["precision"]) / 5
        avg_rec = sum(results[name]["recall"]) / 5
        avg_f1 = sum(results[name]["f1"]) / 5
        avg_tp = sum(results[name]["TP"]) / 5
        avg_tn = sum(results[name]["TN"]) / 5
        avg_fp = sum(results[name]["FP"]) / 5
        avg_fn = sum(results[name]["FN"]) / 5

        print(f"{name}:")
        print(f"  Accuracy={avg_acc:.4f}, Precision={avg_prec:.4f}, Recall={avg_rec:.4f}, F1 Score={avg_f1:.4f}")
        print(f"  Avg TP={avg_tp:.1f}, TN={avg_tn:.1f}, FP={avg_fp:.1f}, FN={avg_fn:.1f}")

In [ ]:
print("\n### K-Fold (No PCA) - full_first ###")
run_kfold_no_pca(full_first)

### K-Fold (No PCA) - full_first ###

===== Fold 1 =====
RandomForest: Accuracy=0.7750, Precision=0.6897, Recall=1.0000, F1=0.8163
        TP=20, TN=11, FP=9, FN=0
SVM: Accuracy=0.5250, Precision=0.5263, Recall=0.5000, F1=0.5128
        TP=10, TN=11, FP=9, FN=10

===== Fold 2 =====
RandomForest: Accuracy=0.6750, Precision=0.6207, Recall=0.9000, F1=0.7347
        TP=18, TN=9, FP=11, FN=2
SVM: Accuracy=0.6000, Precision=0.5909, Recall=0.6500, F1=0.6190
        TP=13, TN=11, FP=9, FN=7

===== Fold 3 =====
RandomForest: Accuracy=0.4500, Precision=0.4167, Recall=0.2500, F1=0.3125
        TP=5, TN=13, FP=7, FN=15
SVM: Accuracy=0.5000, Precision=0.5000, Recall=0.3500, F1=0.4118
        TP=7, TN=13, FP=7, FN=13

===== Fold 4 =====
RandomForest: Accuracy=0.7000, Precision=0.7500, Recall=0.6000, F1=0.6667
        TP=12, TN=16, FP=4, FN=8
SVM: Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9

===== Fold 5 =====
RandomForest: Accuracy=0.5250, Precision=0.5294, Recall=0.4500, F1=0.4865
        TP=9, TN=12, FP=8, FN=11
SVM: Accuracy=0.5000, Precision=0.5000, Recall=0.6000, F1=0.5455
        TP=12, TN=8, FP=12, FN=8

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6250, Precision=0.6013, Recall=0.6400, F1 Score=0.6033
  Avg TP=12.8, TN=12.2, FP=7.8, FN=7.2
SVM:
  Accuracy=0.5300, Precision=0.5282, Recall=0.5300, F1 Score=0.5251
  Avg TP=10.6, TN=10.6, FP=9.4, FN=9.4

In [ ]:
print("\n### K-Fold (No PCA) - full_second ###")
run_kfold_no_pca(full_second)

### K-Fold (No PCA) - full_second ###

===== Fold 1 =====
RandomForest: Accuracy=0.8750, Precision=0.8261, Recall=0.9500, F1=0.8837
        TP=19, TN=16, FP=4, FN=1
SVM: Accuracy=0.5250, Precision=0.5185, Recall=0.7000, F1=0.5957
        TP=14, TN=7, FP=13, FN=6

===== Fold 2 =====
RandomForest: Accuracy=0.7750, Precision=0.7895, Recall=0.7500, F1=0.7692
        TP=15, TN=16, FP=4, FN=5
SVM: Accuracy=0.4750, Precision=0.4828, Recall=0.7000, F1=0.5714
        TP=14, TN=5, FP=15, FN=6

===== Fold 3 =====
RandomForest: Accuracy=0.4750, Precision=0.4615, Recall=0.3000, F1=0.3636
        TP=6, TN=13, FP=7, FN=14
SVM: Accuracy=0.4250, Precision=0.3636, Recall=0.2000, F1=0.2581
        TP=4, TN=13, FP=7, FN=16

===== Fold 4 =====
RandomForest: Accuracy=0.7500, Precision=0.8125, Recall=0.6500, F1=0.7222
        TP=13, TN=17, FP=3, FN=7
SVM: Accuracy=0.5000, Precision=0.5000, Recall=0.4500, F1=0.4737
        TP=9, TN=11, FP=9, FN=11

===== Fold 5 =====
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.4500, F1=0.4737
        TP=9, TN=11, FP=9, FN=11
SVM: Accuracy=0.3500, Precision=0.3500, Recall=0.3500, F1=0.3500
        TP=7, TN=7, FP=13, FN=13

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6750, Precision=0.6779, Recall=0.6200, F1 Score=0.6425
  Avg TP=12.4, TN=14.6, FP=5.4, FN=7.6
SVM:
  Accuracy=0.4550, Precision=0.4430, Recall=0.4800, F1 Score=0.4498
  Avg TP=9.6, TN=8.6, FP=11.4, FN=10.4

In [ ]:
print("\n### K-Fold (No PCA) - full (ทั้งตาราง) ###")
run_kfold_no_pca(full)

### K-Fold (No PCA) - full (ทั้งตาราง) ###

===== Fold 1 =====
RandomForest: Accuracy=0.8125, Precision=0.7451, Recall=0.9500, F1=0.8352
        TP=38, TN=27, FP=13, FN=2
SVM: Accuracy=0.5125, Precision=0.5102, Recall=0.6250, F1=0.5618
        TP=25, TN=16, FP=24, FN=15

===== Fold 2 =====
RandomForest: Accuracy=0.7000, Precision=0.6818, Recall=0.7500, F1=0.7143
        TP=30, TN=26, FP=14, FN=10
SVM: Accuracy=0.4500, Precision=0.4524, Recall=0.4750, F1=0.4634
        TP=19, TN=17, FP=23, FN=21

===== Fold 3 =====
RandomForest: Accuracy=0.4750, Precision=0.4615, Recall=0.3000, F1=0.3636
        TP=12, TN=26, FP=14, FN=28
SVM: Accuracy=0.4500, Precision=0.4167, Recall=0.2500, F1=0.3125
        TP=10, TN=26, FP=14, FN=30

===== Fold 4 =====
RandomForest: Accuracy=0.7125, Precision=0.7429, Recall=0.6500, F1=0.6933
        TP=26, TN=31, FP=9, FN=14
SVM: Accuracy=0.5125, Precision=0.5128, Recall=0.5000, F1=0.5063
        TP=20, TN=21, FP=19, FN=20

===== Fold 5 =====
RandomForest: Accuracy=0.4875, Precision=0.4848, Recall=0.4000, F1=0.4384
        TP=16, TN=23, FP=17, FN=24
SVM: Accuracy=0.5125, Precision=0.5135, Recall=0.4750, F1=0.4935
        TP=19, TN=22, FP=18, FN=21

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6375, Precision=0.6232, Recall=0.6100, F1 Score=0.6090
  Avg TP=24.4, TN=26.6, FP=13.4, FN=15.6
SVM:
  Accuracy=0.4875, Precision=0.4811, Recall=0.4650, F1 Score=0.4675
  Avg TP=18.6, TN=20.4, FP=19.6, FN=21.4

---
#### 3.2 PCA 95% and 98% variance

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import numpy as np

def run_kfold_with_pca(df, target_col='Paror1Healthy0', kfold_col='kfold', variances=[0.95, 0.98]):
    models = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
        "SVM (Linear)": SVC(kernel='linear'),
    }

    for var in variances:
        print(f"\n===== PCA with Explained Variance = {var} =====")
        results = {name: [] for name in models.keys()}

        for fold in range(1, 6):
            print(f"\n===== Fold {fold} =====")
            train_df = df[df[kfold_col] != fold].reset_index(drop=True)
            valid_df = df[df[kfold_col] == fold].reset_index(drop=True)

            drop_cols = [target_col, kfold_col]
            if 'ForS' in df.columns:
                drop_cols.append('ForS')

            X_train = train_df.drop(columns=drop_cols).values
            y_train = train_df[target_col].values
            X_valid = valid_df.drop(columns=drop_cols).values
            y_valid = valid_df[target_col].values

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_valid_scaled = scaler.transform(X_valid)

            pca = PCA(n_components=var)
            X_train_pca = pca.fit_transform(X_train_scaled)
            X_valid_pca = pca.transform(X_valid_scaled)

            n_components_used = X_train_pca.shape[1]
            print(f"  -> Components to reach {var*100:.0f}% variance: {n_components_used} components")

            for name, model in models.items():
                model.fit(X_train_pca, y_train)
                y_pred = model.predict(X_valid_pca)

                acc = accuracy_score(y_valid, y_pred)
                f1 = f1_score(y_valid, y_pred)
                recall = recall_score(y_valid, y_pred)
                precision = precision_score(y_valid, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_valid, y_pred).ravel()

                results[name].append({
                    'fold': fold,
                    'n_components': n_components_used,
                    'accuracy': acc,
                    'f1_score': f1,
                    'recall': recall,
                    'precision': precision,
                    'tn': tn,
                    'fp': fp,
                    'fn': fn,
                    'tp': tp
                })

                print(f"{name}: Accuracy={acc:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
                print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

        # สรุปค่าเฉลี่ย
        print(f"\n===== Average Performance Across 5 Folds (Explained Variance = {var}) =====")
        for name in results:
            accuracies = [r['accuracy'] for r in results[name]]
            f1s = [r['f1_score'] for r in results[name]]
            recalls = [r['recall'] for r in results[name]]
            precisions = [r['precision'] for r in results[name]]
            tns = [r['tn'] for r in results[name]]
            fps = [r['fp'] for r in results[name]]
            fns = [r['fn'] for r in results[name]]
            tps = [r['tp'] for r in results[name]]
            components = [r['n_components'] for r in results[name]]

            print(f"{name}:")
            print(f"  Accuracy={np.mean(accuracies):.4f}, Precision={np.mean(precisions):.4f}, Recall={np.mean(recalls):.4f}, F1 Score={np.mean(f1s):.4f}")
            print(f"  Avg TP={np.mean(tps):.1f}, TN={np.mean(tns):.1f}, FP={np.mean(fps):.1f}, FN={np.mean(fns):.1f}")
            print(f"  Avg PCA Components Used: {np.mean(components):.1f}")

In [ ]:
print("\n### K-Fold + PCA - full_first ###")
run_kfold_with_pca(full_first)

### K-Fold + PCA - full_first ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 12 components
RandomForest: Accuracy=0.4500, Precision=0.4500, Recall=0.4500, F1=0.4500
        TP=9, TN=9, FP=11, FN=11
SVM (Linear): Accuracy=0.3750, Precision=0.4194, Recall=0.6500, F1=0.5098
        TP=13, TN=2, FP=18, FN=7

===== Fold 2 =====
  -> Components to reach 95% variance: 16 components
RandomForest: Accuracy=0.5500, Precision=0.5417, Recall=0.6500, F1=0.5909
        TP=13, TN=9, FP=11, FN=7
SVM (Linear): Accuracy=0.4500, Precision=0.4444, Recall=0.4000, F1=0.4211
        TP=8, TN=10, FP=10, FN=12

===== Fold 3 =====
  -> Components to reach 95% variance: 18 components
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.4000, F1=0.4444
        TP=8, TN=12, FP=8, FN=12
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.2500, F1=0.3333
        TP=5, TN=15, FP=5, FN=15

===== Fold 4 =====
  -> Components to reach 95% variance: 14 components
RandomForest: Accuracy=0.4250, Precision=0.4400, Recall=0.5500, F1=0.4889
        TP=11, TN=6, FP=14, FN=9
SVM (Linear): Accuracy=0.3750, Precision=0.4242, Recall=0.7000, F1=0.5283
        TP=14, TN=1, FP=19, FN=6

===== Fold 5 =====
  -> Components to reach 95% variance: 13 components
RandomForest: Accuracy=0.4750, Precision=0.4815, Recall=0.6500, F1=0.5532
        TP=13, TN=6, FP=14, FN=7
SVM (Linear): Accuracy=0.4500, Precision=0.4286, Recall=0.3000, F1=0.3529
        TP=6, TN=12, FP=8, FN=14

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.4800, Precision=0.4826, Recall=0.5400, F1 Score=0.5055
  Avg TP=10.8, TN=8.4, FP=11.6, FN=9.2
  Avg PCA Components Used: 14.6
SVM (Linear):
  Accuracy=0.4300, Precision=0.4433, Recall=0.4600, F1 Score=0.4291
  Avg TP=9.2, TN=8.0, FP=12.0, FN=10.8
  Avg PCA Components Used: 14.6

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 41 components
RandomForest: Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9
SVM (Linear): Accuracy=0.5750, Precision=0.5652, Recall=0.6500, F1=0.6047
        TP=13, TN=10, FP=10, FN=7

===== Fold 2 =====
  -> Components to reach 98% variance: 33 components
RandomForest: Accuracy=0.6250, Precision=0.6087, Recall=0.7000, F1=0.6512
        TP=14, TN=11, FP=9, FN=6
SVM (Linear): Accuracy=0.6250, Precision=0.6190, Recall=0.6500, F1=0.6341
        TP=13, TN=12, FP=8, FN=7

===== Fold 3 =====
  -> Components to reach 98% variance: 54 components
RandomForest: Accuracy=0.4500, Precision=0.3750, Recall=0.1500, F1=0.2143
        TP=3, TN=15, FP=5, FN=17
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.3500, F1=0.4118
        TP=7, TN=13, FP=7, FN=13

===== Fold 4 =====
  -> Components to reach 98% variance: 47 components
RandomForest: Accuracy=0.6500, Precision=0.7143, Recall=0.5000, F1=0.5882
        TP=10, TN=16, FP=4, FN=10
SVM (Linear): Accuracy=0.4250, Precision=0.4444, Recall=0.6000, F1=0.5106
        TP=12, TN=5, FP=15, FN=8

===== Fold 5 =====
  -> Components to reach 98% variance: 45 components
RandomForest: Accuracy=0.5250, Precision=0.5263, Recall=0.5000, F1=0.5128
        TP=10, TN=11, FP=9, FN=10
SVM (Linear): Accuracy=0.5500, Precision=0.5556, Recall=0.5000, F1=0.5263
        TP=10, TN=12, FP=8, FN=10

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5550, Precision=0.5496, Recall=0.4800, F1 Score=0.5006
  Avg TP=9.6, TN=12.6, FP=7.4, FN=10.4
  Avg PCA Components Used: 44.0
SVM (Linear):
  Accuracy=0.5350, Precision=0.5369, Recall=0.5500, F1 Score=0.5375
  Avg TP=11.0, TN=10.4, FP=9.6, FN=9.0
  Avg PCA Components Used: 44.0

In [ ]:
print("\n### K-Fold + PCA - full_second ###")
run_kfold_with_pca(full_second)

### K-Fold + PCA - full_second ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 16 components
RandomForest: Accuracy=0.6750, Precision=0.6296, Recall=0.8500, F1=0.7234
        TP=17, TN=10, FP=10, FN=3
SVM (Linear): Accuracy=0.4250, Precision=0.4595, Recall=0.8500, F1=0.5965
        TP=17, TN=0, FP=20, FN=3

===== Fold 2 =====
  -> Components to reach 95% variance: 20 components
RandomForest: Accuracy=0.6500, Precision=0.6364, Recall=0.7000, F1=0.6667
        TP=14, TN=12, FP=8, FN=6
SVM (Linear): Accuracy=0.5250, Precision=0.5385, Recall=0.3500, F1=0.4242
        TP=7, TN=14, FP=6, FN=13

===== Fold 3 =====
  -> Components to reach 95% variance: 22 components
RandomForest: Accuracy=0.5250, Precision=0.5217, Recall=0.6000, F1=0.5581
        TP=12, TN=9, FP=11, FN=8
SVM (Linear): Accuracy=0.4750, Precision=0.4762, Recall=0.5000, F1=0.4878
        TP=10, TN=9, FP=11, FN=10

===== Fold 4 =====
  -> Components to reach 95% variance: 17 components
RandomForest: Accuracy=0.5250, Precision=0.5385, Recall=0.3500, F1=0.4242
        TP=7, TN=14, FP=6, FN=13
SVM (Linear): Accuracy=0.5750, Precision=0.5600, Recall=0.7000, F1=0.6222
        TP=14, TN=9, FP=11, FN=6

===== Fold 5 =====
  -> Components to reach 95% variance: 14 components
RandomForest: Accuracy=0.4750, Precision=0.4800, Recall=0.6000, F1=0.5333
        TP=12, TN=7, FP=13, FN=8
SVM (Linear): Accuracy=0.3750, Precision=0.3077, Recall=0.2000, F1=0.2424
        TP=4, TN=11, FP=9, FN=16

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.5700, Precision=0.5612, Recall=0.6200, F1 Score=0.5812
  Avg TP=12.4, TN=10.4, FP=9.6, FN=7.6
  Avg PCA Components Used: 17.8
SVM (Linear):
  Accuracy=0.4750, Precision=0.4684, Recall=0.5200, F1 Score=0.4746
  Avg TP=10.4, TN=8.6, FP=11.4, FN=9.6
  Avg PCA Components Used: 17.8

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 42 components
RandomForest: Accuracy=0.6500, Precision=0.7143, Recall=0.5000, F1=0.5882
        TP=10, TN=16, FP=4, FN=10
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.5500, F1=0.5238
        TP=11, TN=9, FP=11, FN=9

===== Fold 2 =====
  -> Components to reach 98% variance: 34 components
RandomForest: Accuracy=0.7750, Precision=0.7619, Recall=0.8000, F1=0.7805
        TP=16, TN=15, FP=5, FN=4
SVM (Linear): Accuracy=0.6250, Precision=0.8571, Recall=0.3000, F1=0.4444
        TP=6, TN=19, FP=1, FN=14

===== Fold 3 =====
  -> Components to reach 98% variance: 48 components
RandomForest: Accuracy=0.4000, Precision=0.3333, Recall=0.2000, F1=0.2500
        TP=4, TN=12, FP=8, FN=16
SVM (Linear): Accuracy=0.4500, Precision=0.4500, Recall=0.4500, F1=0.4500
        TP=9, TN=9, FP=11, FN=11

===== Fold 4 =====
  -> Components to reach 98% variance: 43 components
RandomForest: Accuracy=0.6750, Precision=0.7692, Recall=0.5000, F1=0.6061
        TP=10, TN=17, FP=3, FN=10
SVM (Linear): Accuracy=0.6250, Precision=0.6316, Recall=0.6000, F1=0.6154
        TP=12, TN=13, FP=7, FN=8

===== Fold 5 =====
  -> Components to reach 98% variance: 37 components
RandomForest: Accuracy=0.3000, Precision=0.3333, Recall=0.4000, F1=0.3636
        TP=8, TN=4, FP=16, FN=12
SVM (Linear): Accuracy=0.3500, Precision=0.3125, Recall=0.2500, F1=0.2778
        TP=5, TN=9, FP=11, FN=15

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5600, Precision=0.5824, Recall=0.4800, F1 Score=0.5177
  Avg TP=9.6, TN=12.8, FP=7.2, FN=10.4
  Avg PCA Components Used: 40.8
SVM (Linear):
  Accuracy=0.5100, Precision=0.5502, Recall=0.4300, F1 Score=0.4623
  Avg TP=8.6, TN=11.8, FP=8.2, FN=11.4
  Avg PCA Components Used: 40.8

In [ ]:
print("\n### K-Fold + PCA - full (ทั้งตาราง) ###")
run_kfold_with_pca(full)

### K-Fold + PCA - full (ทั้งตาราง) ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 25 components
RandomForest: Accuracy=0.5625, Precision=0.5610, Recall=0.5750, F1=0.5679
        TP=23, TN=22, FP=18, FN=17
SVM (Linear): Accuracy=0.4125, Precision=0.4507, Recall=0.8000, F1=0.5766
        TP=32, TN=1, FP=39, FN=8

===== Fold 2 =====
  -> Components to reach 95% variance: 31 components
RandomForest: Accuracy=0.6375, Precision=0.6222, Recall=0.7000, F1=0.6588
        TP=28, TN=23, FP=17, FN=12
SVM (Linear): Accuracy=0.5125, Precision=0.5152, Recall=0.4250, F1=0.4658
        TP=17, TN=24, FP=16, FN=23

===== Fold 3 =====
  -> Components to reach 95% variance: 37 components
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.4500, F1=0.4737
        TP=18, TN=22, FP=18, FN=22
SVM (Linear): Accuracy=0.5500, Precision=0.6111, Recall=0.2750, F1=0.3793
        TP=11, TN=33, FP=7, FN=29

===== Fold 4 =====
  -> Components to reach 95% variance: 28 components
RandomForest: Accuracy=0.4625, Precision=0.4571, Recall=0.4000, F1=0.4267
        TP=16, TN=21, FP=19, FN=24
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.7000, F1=0.5833
        TP=28, TN=12, FP=28, FN=12

===== Fold 5 =====
  -> Components to reach 95% variance: 23 components
RandomForest: Accuracy=0.4250, Precision=0.4250, Recall=0.4250, F1=0.4250
        TP=17, TN=17, FP=23, FN=23
SVM (Linear): Accuracy=0.3500, Precision=0.2273, Recall=0.1250, F1=0.1613
        TP=5, TN=23, FP=17, FN=35

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.5175, Precision=0.5131, Recall=0.5100, F1 Score=0.5104
  Avg TP=20.4, TN=21.0, FP=19.0, FN=19.6
  Avg PCA Components Used: 28.8
SVM (Linear):
  Accuracy=0.4650, Precision=0.4608, Recall=0.4650, F1 Score=0.4333
  Avg TP=18.6, TN=18.6, FP=21.4, FN=21.4
  Avg PCA Components Used: 28.8

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 80 components
RandomForest: Accuracy=0.7125, Precision=0.7297, Recall=0.6750, F1=0.7013
        TP=27, TN=30, FP=10, FN=13
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.4500, F1=0.4737
        TP=18, TN=22, FP=18, FN=22

===== Fold 2 =====
  -> Components to reach 98% variance: 64 components
RandomForest: Accuracy=0.7000, Precision=0.6667, Recall=0.8000, F1=0.7273
        TP=32, TN=24, FP=16, FN=8
SVM (Linear): Accuracy=0.5500, Precision=0.5556, Recall=0.5000, F1=0.5263
        TP=20, TN=24, FP=16, FN=20

===== Fold 3 =====
  -> Components to reach 98% variance: 97 components
RandomForest: Accuracy=0.3625, Precision=0.0769, Recall=0.0250, F1=0.0377
        TP=1, TN=28, FP=12, FN=39
SVM (Linear): Accuracy=0.6000, Precision=0.6538, Recall=0.4250, F1=0.5152
        TP=17, TN=31, FP=9, FN=23

===== Fold 4 =====
  -> Components to reach 98% variance: 86 components
RandomForest: Accuracy=0.5625, Precision=0.6923, Recall=0.2250, F1=0.3396
        TP=9, TN=36, FP=4, FN=31
SVM (Linear): Accuracy=0.6250, Precision=0.6000, Recall=0.7500, F1=0.6667
        TP=30, TN=20, FP=20, FN=10

===== Fold 5 =====
  -> Components to reach 98% variance: 78 components
RandomForest: Accuracy=0.3625, Precision=0.3103, Recall=0.2250, F1=0.2609
        TP=9, TN=20, FP=20, FN=31
SVM (Linear): Accuracy=0.4750, Precision=0.4737, Recall=0.4500, F1=0.4615
        TP=18, TN=20, FP=20, FN=22

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5400, Precision=0.4952, Recall=0.3900, F1 Score=0.4134
  Avg TP=15.6, TN=27.6, FP=12.4, FN=24.4
  Avg PCA Components Used: 81.0
SVM (Linear):
  Accuracy=0.5500, Precision=0.5566, Recall=0.5150, F1 Score=0.5287
  Avg TP=20.6, TN=23.4, FP=16.6, FN=19.4
  Avg PCA Components Used: 81.0