<a href="https://colab.research.google.com/github/sitthatkaja/ParkinsonAIModel/blob/main/%5BClassification%5D_Non_NormalFA_3_Frame_Average.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Classification] Non NormalFA 3 Frame Average

This colab is a code for Classification (Parkinson or not) for ``` 3 Frame Average in 3 Facial Action Scenario following: Non-Smile, Smile, and Combine``` introducing methodology.

***Note: if you have any problem please check in my github: https://github.com/sitthatkaja/ParkinsonAIModel***

---

## 1. Data Input
---

This section you need to input data form data collect in github. This setep is depend on user. You can use  ``` Google sheet link with google Drive ``` to import Data.

***Note: This section is not to shown because a privacy of account.***

## 2. Data Preprocessing
---

Form my input this is sliding video to half for  `3 Facial Action Scenarios following: Non-Smile, Smile, and Combine` that is mean the data should be counting of half it (35450 Columns in 3 Frame Average)


***note: This method have something wrong or error of colab including: number of column. you can ignore it.***

In [ ]:
for i in range(1, len(dfs) + 1):
    globals()[f'df{i}'] = dfs[f'df{i}']

In [ ]:
df1.head()

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.98,1,0.174402,0.173605,-0.969250,-0.139685,0.230682,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
1,2,0,0.033,0.98,1,0.179208,0.177269,-0.967709,-0.160462,0.249239,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
2,3,0,0.067,0.98,1,0.175176,0.168792,-0.969960,-0.153304,0.236380,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,4,0,0.100,0.98,1,0.178275,0.167154,-0.969679,-0.161075,0.229773,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,5,0,0.133,0.98,1,0.185327,0.163628,-0.968958,-0.151368,0.231574,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [ ]:
dfss = [globals()[f'df{i}'] for i in range(1, len(dfs) + 1)]

In [ ]:
for i in range(len(dfss)):
    dfss[i] = dfss[i].iloc[:, 5:]

In [ ]:
averaged_tables = []  # เก็บ DataFrame ของค่าเฉลี่ยแต่ละตาราง

for df in dfss:
    # ตรวจสอบว่าตารางมีจำนวนแถวอย่างน้อย 300 แถว
    df = df.iloc[:300]  # เลือกเฉพาะ 300 แถวแรก
    averaged_rows = []

    # หาค่าเฉลี่ยทุกๆ 3 แถว
    for i in range(0, 300, 3):
        averaged_row = df.iloc[i:i+3].mean()
        averaged_rows.append(averaged_row)

    # สร้าง DataFrame ใหม่สำหรับตารางที่ผ่านการเฉลี่ยแล้ว และเพิ่มลงใน averaged_tables
    averaged_table = pd.DataFrame(averaged_rows)
    averaged_tables.append(averaged_table)

In [ ]:
averaged_tables[0]

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,eye_lmk_x_0,eye_lmk_x_1,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,0.176262,0.173222,-0.968973,-0.151150,0.238767,-0.959166,0.013000,0.210333,432.033333,437.933333,...,0.0,0.0,1.0,0.0,1.0,1.000000,0.0,0.0,0.0,1.0
1,0.181377,0.167047,-0.969114,-0.155923,0.230910,-0.960392,0.013333,0.203333,427.500000,433.533333,...,0.0,0.0,1.0,0.0,1.0,0.666667,0.0,0.0,0.0,1.0
2,0.184647,0.173706,-0.967315,-0.153816,0.232745,-0.960285,0.016000,0.208000,422.633333,429.000000,...,0.0,0.0,1.0,0.0,1.0,1.000000,0.0,0.0,0.0,1.0
3,0.177843,0.175828,-0.968210,-0.149603,0.233402,-0.960791,0.014667,0.209000,423.233333,429.533333,...,0.0,0.0,1.0,0.0,1.0,1.000000,0.0,0.0,0.0,1.0
4,0.174658,0.169500,-0.969918,-0.157289,0.211865,-0.964547,0.009000,0.194667,424.366667,430.633333,...,0.0,0.0,1.0,0.0,1.0,1.000000,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in range(len(averaged_tables)):
    df = averaged_tables[i]
    # รวมแถวทั้งหมดให้เป็น 1 row
    flattened_row = pd.concat([df.iloc[j] for j in range(len(df))]).reset_index(drop=True)

    # แปลงกลับเป็น DataFrame ที่มี 1 แถว
    averaged_tables[i] = pd.DataFrame([flattened_row])

In [ ]:
full = pd.concat(averaged_tables, axis=0).reset_index(drop=True)
full

,0,1,2,3,4,5,6,7,8,9,...,70890,70891,70892,70893,70894,70895,70896,70897,70898,70899
0,0.176262,0.173222,-0.968973,-0.151150,0.238767,-0.959166,0.013000,0.210333,432.033333,437.933333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.178758,0.253048,-0.950485,-0.111842,0.253746,-0.960717,0.034667,0.259000,394.366667,400.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.169337,0.279944,-0.944533,-0.102729,0.286949,-0.952331,0.035000,0.290333,467.600000,473.966667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.118490,0.237406,-0.964062,-0.190986,0.342539,-0.919758,-0.038667,0.298667,367.433333,370.566667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.210670,0.267058,-0.940332,-0.059993,0.315722,-0.946863,0.079333,0.299667,375.500000,380.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.018681,0.211573,-0.977018,-0.046943,0.182481,-0.981416,-0.014333,0.198333,461.733333,466.966667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,0.025877,0.189666,-0.981490,-0.070827,0.160830,-0.984424,-0.023000,0.176667,484.466667,490.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,0.020239,0.179239,-0.983573,-0.042217,0.149980,-0.987659,-0.011000,0.165667,476.766667,481.766667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,0.026601,0.209741,-0.977362,-0.055480,0.161973,-0.985228,-0.014667,0.187000,461.100000,466.266667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,0.033171,0.232097,-0.972043,-0.051155,0.186135,-0.981052,-0.009333,0.211000,470.933333,476.300000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
full = full.iloc[:,:35450]
full

,0,1,2,3,4,5,6,7,8,9,...,34022,34023,34024,34025,34026,34027,34028,34029,34030,34031
0,0.176262,0.173222,-0.968973,-0.151150,0.238767,-0.959166,0.013000,0.210333,432.033333,437.933333,...,0.000000,0.0,0.666667,0.000000,1.0,0.333333,0.0,0.0,0.000000,1.0
1,0.178758,0.253048,-0.950485,-0.111842,0.253746,-0.960717,0.034667,0.259000,394.366667,400.500000,...,0.000000,0.0,1.000000,0.000000,1.0,1.000000,0.0,0.0,0.000000,1.0
2,0.169337,0.279944,-0.944533,-0.102729,0.286949,-0.952331,0.035000,0.290333,467.600000,473.966667,...,0.000000,0.0,1.000000,0.000000,0.0,1.000000,0.0,0.0,0.333333,1.0
3,0.118490,0.237406,-0.964062,-0.190986,0.342539,-0.919758,-0.038667,0.298667,367.433333,370.566667,...,0.000000,0.0,1.000000,0.000000,1.0,1.000000,0.0,0.0,0.000000,1.0
4,0.210670,0.267058,-0.940332,-0.059993,0.315722,-0.946863,0.079333,0.299667,375.500000,380.900000,...,0.000000,0.0,1.000000,0.000000,0.0,1.000000,0.0,0.0,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.018681,0.211573,-0.977018,-0.046943,0.182481,-0.981416,-0.014333,0.198333,461.733333,466.966667,...,1.000000,0.0,0.666667,0.666667,1.0,0.000000,1.0,0.0,0.000000,1.0
396,0.025877,0.189666,-0.981490,-0.070827,0.160830,-0.984424,-0.023000,0.176667,484.466667,490.333333,...,1.000000,0.0,1.000000,1.000000,1.0,0.000000,0.0,0.0,0.000000,1.0
397,0.020239,0.179239,-0.983573,-0.042217,0.149980,-0.987659,-0.011000,0.165667,476.766667,481.766667,...,0.666667,0.0,1.000000,0.666667,1.0,0.000000,1.0,0.0,0.000000,1.0
398,0.026601,0.209741,-0.977362,-0.055480,0.161973,-0.985228,-0.014667,0.187000,461.100000,466.266667,...,1.000000,0.0,1.000000,1.000000,1.0,1.000000,1.0,0.0,0.000000,1.0
399,0.033171,0.232097,-0.972043,-0.051155,0.186135,-0.981052,-0.009333,0.211000,470.933333,476.300000,...,1.000000,0.0,1.000000,1.000000,1.0,1.000000,1.0,0.0,0.000000,1.0

In [ ]:
full.isnull().values.any()

np.False_

## 3. Modeling
---
This section is Modeling when you prepare data form data preprocessing. This method, You should to try setup form other side and coding following: PCA and 3 Models.

***Note: This section in for experimental for all. It's means some value is non-using for report.***

3.1 NO PCA

In [ ]:
status = df[['Paror1Healthy0', 'kfold','ForS']]
status

     Paror1Healthy0  kfold  ForS
0                 1      1     1
1                 1      1     1
2                 1      1     1
3                 1      1     1
4                 1      1     1
..              ...    ...   ...
395               0      5     2
396               0      5     2
397               0      5     2
398               0      5     2
399               0      5     2

[400 rows x 3 columns]

In [ ]:
full = pd.concat([status,full], axis=1)
full

,Paror1Healthy0,kfold,ForS,0,1,2,3,4,5,6,...,34022,34023,34024,34025,34026,34027,34028,34029,34030,34031
0,1,1,1,0.176262,0.173222,-0.968973,-0.151150,0.238767,-0.959166,0.013000,...,0.000000,0.0,0.666667,0.000000,1.0,0.333333,0.0,0.0,0.000000,1.0
1,1,1,1,0.178758,0.253048,-0.950485,-0.111842,0.253746,-0.960717,0.034667,...,0.000000,0.0,1.000000,0.000000,1.0,1.000000,0.0,0.0,0.000000,1.0
2,1,1,1,0.169337,0.279944,-0.944533,-0.102729,0.286949,-0.952331,0.035000,...,0.000000,0.0,1.000000,0.000000,0.0,1.000000,0.0,0.0,0.333333,1.0
3,1,1,1,0.118490,0.237406,-0.964062,-0.190986,0.342539,-0.919758,-0.038667,...,0.000000,0.0,1.000000,0.000000,1.0,1.000000,0.0,0.0,0.000000,1.0
4,1,1,1,0.210670,0.267058,-0.940332,-0.059993,0.315722,-0.946863,0.079333,...,0.000000,0.0,1.000000,0.000000,0.0,1.000000,0.0,0.0,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,5,2,0.018681,0.211573,-0.977018,-0.046943,0.182481,-0.981416,-0.014333,...,1.000000,0.0,0.666667,0.666667,1.0,0.000000,1.0,0.0,0.000000,1.0
396,0,5,2,0.025877,0.189666,-0.981490,-0.070827,0.160830,-0.984424,-0.023000,...,1.000000,0.0,1.000000,1.000000,1.0,0.000000,0.0,0.0,0.000000,1.0
397,0,5,2,0.020239,0.179239,-0.983573,-0.042217,0.149980,-0.987659,-0.011000,...,0.666667,0.0,1.000000,0.666667,1.0,0.000000,1.0,0.0,0.000000,1.0
398,0,5,2,0.026601,0.209741,-0.977362,-0.055480,0.161973,-0.985228,-0.014667,...,1.000000,0.0,1.000000,1.000000,1.0,1.000000,1.0,0.0,0.000000,1.0
399,0,5,2,0.033171,0.232097,-0.972043,-0.051155,0.186135,-0.981052,-0.009333,...,1.000000,0.0,1.000000,1.000000,1.0,1.000000,1.0,0.0,0.000000,1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
# แยก full ตาม ForS
full_first = full[full['ForS'] == 1].reset_index(drop=True)
full_second = full[full['ForS'] == 2].reset_index(drop=True)
# full เดิมคือทั้งครึ่งแรกและครึ่งหลัง

In [ ]:
def run_kfold_no_pca(df, target_col='Paror1Healthy0', kfold_col='kfold'):
    models = {
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel="linear")
    }

    results = {name: {
        "accuracy": [], "precision": [], "recall": [], "f1": [],
        "TP": [], "TN": [], "FP": [], "FN": []
    } for name in models}

    for fold in range(1, 6):
        print(f"\n===== Fold {fold} =====")
        df_train = df[df[kfold_col] != fold].reset_index(drop=True)
        df_valid = df[df[kfold_col] == fold].reset_index(drop=True)

        # ดรอป target, kfold, ForS (ถ้ามี) ออกจาก X
        drop_cols = [target_col, kfold_col]
        if 'ForS' in df.columns:
            drop_cols.append('ForS')

        X_train = df_train.drop(columns=drop_cols)
        y_train = df_train[target_col]
        X_valid = df_valid.drop(columns=drop_cols)
        y_valid = df_valid[target_col]

        for name, model in models.items():
            model.fit(X_train, y_train)
            preds = model.predict(X_valid)

            accuracy = accuracy_score(y_valid, preds)
            precision = precision_score(y_valid, preds, average='binary')
            recall = recall_score(y_valid, preds, average='binary')
            f1 = f1_score(y_valid, preds, average='binary')
            tn, fp, fn, tp = confusion_matrix(y_valid, preds).ravel()

            results[name]["accuracy"].append(accuracy)
            results[name]["precision"].append(precision)
            results[name]["recall"].append(recall)
            results[name]["f1"].append(f1)
            results[name]["TP"].append(tp)
            results[name]["TN"].append(tn)
            results[name]["FP"].append(fp)
            results[name]["FN"].append(fn)

            print(f"{name}: Accuracy={accuracy:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
            print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

    # สรุปค่าเฉลี่ยแต่ละโมเดล
    print("\n===== Average Performance Across 5 Folds =====")
    for name in models:
        avg_acc = sum(results[name]["accuracy"]) / 5
        avg_prec = sum(results[name]["precision"]) / 5
        avg_rec = sum(results[name]["recall"]) / 5
        avg_f1 = sum(results[name]["f1"]) / 5
        avg_tp = sum(results[name]["TP"]) / 5
        avg_tn = sum(results[name]["TN"]) / 5
        avg_fp = sum(results[name]["FP"]) / 5
        avg_fn = sum(results[name]["FN"]) / 5

        print(f"{name}:")
        print(f"  Accuracy={avg_acc:.4f}, Precision={avg_prec:.4f}, Recall={avg_rec:.4f}, F1 Score={avg_f1:.4f}")
        print(f"  Avg TP={avg_tp:.1f}, TN={avg_tn:.1f}, FP={avg_fp:.1f}, FN={avg_fn:.1f}")

In [ ]:
print("\n### K-Fold (No PCA) - full_first ###")
run_kfold_no_pca(full_first)

### K-Fold (No PCA) - full_first ###

===== Fold 1 =====
RandomForest: Accuracy=0.8250, Precision=1.0000, Recall=0.6500, F1=0.7879
        TP=13, TN=20, FP=0, FN=7
SVM: Accuracy=0.6000, Precision=0.6429, Recall=0.4500, F1=0.5294
        TP=9, TN=15, FP=5, FN=11

===== Fold 2 =====
RandomForest: Accuracy=0.7750, Precision=0.7619, Recall=0.8000, F1=0.7805
        TP=16, TN=15, FP=5, FN=4
SVM: Accuracy=0.6250, Precision=0.6190, Recall=0.6500, F1=0.6341
        TP=13, TN=12, FP=8, FN=7

===== Fold 3 =====
RandomForest: Accuracy=0.5250, Precision=0.5172, Recall=0.7500, F1=0.6122
        TP=15, TN=6, FP=14, FN=5
SVM: Accuracy=0.3500, Precision=0.3929, Recall=0.5500, F1=0.4583
        TP=11, TN=3, FP=17, FN=9

===== Fold 4 =====
RandomForest: Accuracy=0.6500, Precision=0.6875, Recall=0.5500, F1=0.6111
        TP=11, TN=15, FP=5, FN=9
SVM: Accuracy=0.4750, Precision=0.4000, Recall=0.1000, F1=0.1600
        TP=2, TN=17, FP=3, FN=18

===== Fold 5 =====
RandomForest: Accuracy=0.4000, Precision=0.3571, Recall=0.2500, F1=0.2941
        TP=5, TN=11, FP=9, FN=15
SVM: Accuracy=0.4750, Precision=0.4545, Recall=0.2500, F1=0.3226
        TP=5, TN=14, FP=6, FN=15

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6350, Precision=0.6648, Recall=0.6000, F1 Score=0.6172
  Avg TP=12.0, TN=13.4, FP=6.6, FN=8.0
SVM:
  Accuracy=0.5050, Precision=0.5019, Recall=0.4000, F1 Score=0.4209
  Avg TP=8.0, TN=12.2, FP=7.8, FN=12.0

In [ ]:
print("\n### K-Fold (No PCA) - full_second ###")
run_kfold_no_pca(full_second)

### K-Fold (No PCA) - full_second ###

===== Fold 1 =====
RandomForest: Accuracy=0.9000, Precision=1.0000, Recall=0.8000, F1=0.8889
        TP=16, TN=20, FP=0, FN=4
SVM: Accuracy=0.8250, Precision=0.7407, Recall=1.0000, F1=0.8511
        TP=20, TN=13, FP=7, FN=0

===== Fold 2 =====
RandomForest: Accuracy=0.8000, Precision=0.7727, Recall=0.8500, F1=0.8095
        TP=17, TN=15, FP=5, FN=3
SVM: Accuracy=0.6500, Precision=0.7143, Recall=0.5000, F1=0.5882
        TP=10, TN=16, FP=4, FN=10

===== Fold 3 =====
RandomForest: Accuracy=0.4500, Precision=0.4643, Recall=0.6500, F1=0.5417
        TP=13, TN=5, FP=15, FN=7
SVM: Accuracy=0.2750, Precision=0.2632, Recall=0.2500, F1=0.2564
        TP=5, TN=6, FP=14, FN=15

===== Fold 4 =====
RandomForest: Accuracy=0.6000, Precision=0.6429, Recall=0.4500, F1=0.5294
        TP=9, TN=15, FP=5, FN=11
SVM: Accuracy=0.5500, Precision=0.7500, Recall=0.1500, F1=0.2500
        TP=3, TN=19, FP=1, FN=17

===== Fold 5 =====
RandomForest: Accuracy=0.5250, Precision=0.5294, Recall=0.4500, F1=0.4865
        TP=9, TN=12, FP=8, FN=11
SVM: Accuracy=0.3500, Precision=0.2500, Recall=0.1500, F1=0.1875
        TP=3, TN=11, FP=9, FN=17

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.6550, Precision=0.6819, Recall=0.6400, F1 Score=0.6512
  Avg TP=12.8, TN=13.4, FP=6.6, FN=7.2
SVM:
  Accuracy=0.5300, Precision=0.5436, Recall=0.4100, F1 Score=0.4266
  Avg TP=8.2, TN=13.0, FP=7.0, FN=11.8

In [ ]:
print("\n### K-Fold (No PCA) - full (ทั้งตาราง) ###")
run_kfold_no_pca(full)

### K-Fold (No PCA) - full (ทั้งตาราง) ###

===== Fold 1 =====
RandomForest: Accuracy=0.7500, Precision=1.0000, Recall=0.5000, F1=0.6667
        TP=20, TN=40, FP=0, FN=20
SVM: Accuracy=0.7375, Precision=0.7568, Recall=0.7000, F1=0.7273
        TP=28, TN=31, FP=9, FN=12

===== Fold 2 =====
RandomForest: Accuracy=0.7500, Precision=0.7632, Recall=0.7250, F1=0.7436
        TP=29, TN=31, FP=9, FN=11
SVM: Accuracy=0.6000, Precision=0.6176, Recall=0.5250, F1=0.5676
        TP=21, TN=27, FP=13, FN=19

===== Fold 3 =====
RandomForest: Accuracy=0.5000, Precision=0.5000, Recall=0.7250, F1=0.5918
        TP=29, TN=11, FP=29, FN=11
SVM: Accuracy=0.2750, Precision=0.3448, Recall=0.5000, F1=0.4082
        TP=20, TN=2, FP=38, FN=20

===== Fold 4 =====
RandomForest: Accuracy=0.5750, Precision=0.6154, Recall=0.4000, F1=0.4848
        TP=16, TN=30, FP=10, FN=24
SVM: Accuracy=0.4375, Precision=0.3333, Recall=0.1250, F1=0.1818
        TP=5, TN=30, FP=10, FN=35

===== Fold 5 =====
RandomForest: Accuracy=0.4125, Precision=0.3704, Recall=0.2500, F1=0.2985
        TP=10, TN=23, FP=17, FN=30
SVM: Accuracy=0.3750, Precision=0.3333, Recall=0.2500, F1=0.2857
        TP=10, TN=20, FP=20, FN=30

===== Average Performance Across 5 Folds =====
RandomForest:
  Accuracy=0.5975, Precision=0.6498, Recall=0.5200, F1 Score=0.5571
  Avg TP=20.8, TN=27.0, FP=13.0, FN=19.2
SVM:
  Accuracy=0.4850, Precision=0.4772, Recall=0.4200, F1 Score=0.4341
  Avg TP=16.8, TN=22.0, FP=18.0, FN=23.2

---
#### 3.2 PCA 95% and 98% variance

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import numpy as np

def run_kfold_with_pca(df, target_col='Paror1Healthy0', kfold_col='kfold', variances=[0.95, 0.98]):
    models = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
        "SVM (Linear)": SVC(kernel='linear'),
    }

    for var in variances:
        print(f"\n===== PCA with Explained Variance = {var} =====")
        results = {name: [] for name in models.keys()}

        for fold in range(1, 6):
            print(f"\n===== Fold {fold} =====")
            train_df = df[df[kfold_col] != fold].reset_index(drop=True)
            valid_df = df[df[kfold_col] == fold].reset_index(drop=True)

            drop_cols = [target_col, kfold_col]
            if 'ForS' in df.columns:
                drop_cols.append('ForS')

            X_train = train_df.drop(columns=drop_cols).values
            y_train = train_df[target_col].values
            X_valid = valid_df.drop(columns=drop_cols).values
            y_valid = valid_df[target_col].values

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_valid_scaled = scaler.transform(X_valid)

            pca = PCA(n_components=var)
            X_train_pca = pca.fit_transform(X_train_scaled)
            X_valid_pca = pca.transform(X_valid_scaled)

            n_components_used = X_train_pca.shape[1]
            print(f"  -> Components to reach {var*100:.0f}% variance: {n_components_used} components")

            for name, model in models.items():
                model.fit(X_train_pca, y_train)
                y_pred = model.predict(X_valid_pca)

                acc = accuracy_score(y_valid, y_pred)
                f1 = f1_score(y_valid, y_pred)
                recall = recall_score(y_valid, y_pred)
                precision = precision_score(y_valid, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_valid, y_pred).ravel()

                results[name].append({
                    'fold': fold,
                    'n_components': n_components_used,
                    'accuracy': acc,
                    'f1_score': f1,
                    'recall': recall,
                    'precision': precision,
                    'tn': tn,
                    'fp': fp,
                    'fn': fn,
                    'tp': tp
                })

                print(f"{name}: Accuracy={acc:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
                print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

        # สรุปค่าเฉลี่ย
        print(f"\n===== Average Performance Across 5 Folds (Explained Variance = {var}) =====")
        for name in results:
            accuracies = [r['accuracy'] for r in results[name]]
            f1s = [r['f1_score'] for r in results[name]]
            recalls = [r['recall'] for r in results[name]]
            precisions = [r['precision'] for r in results[name]]
            tns = [r['tn'] for r in results[name]]
            fps = [r['fp'] for r in results[name]]
            fns = [r['fn'] for r in results[name]]
            tps = [r['tp'] for r in results[name]]
            components = [r['n_components'] for r in results[name]]

            print(f"{name}:")
            print(f"  Accuracy={np.mean(accuracies):.4f}, Precision={np.mean(precisions):.4f}, Recall={np.mean(recalls):.4f}, F1 Score={np.mean(f1s):.4f}")
            print(f"  Avg TP={np.mean(tps):.1f}, TN={np.mean(tns):.1f}, FP={np.mean(fps):.1f}, FN={np.mean(fns):.1f}")
            print(f"  Avg PCA Components Used: {np.mean(components):.1f}")

In [ ]:
print("\n### K-Fold + PCA - full_first ###")
run_kfold_with_pca(full_first)

### K-Fold + PCA - full_first ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 20 components
RandomForest: Accuracy=0.8250, Precision=0.8824, Recall=0.7500, F1=0.8108
        TP=15, TN=18, FP=2, FN=5
SVM (Linear): Accuracy=0.8000, Precision=0.7500, Recall=0.9000, F1=0.8182
        TP=18, TN=14, FP=6, FN=2

===== Fold 2 =====
  -> Components to reach 95% variance: 23 components
RandomForest: Accuracy=0.6250, Precision=0.6667, Recall=0.5000, F1=0.5714
        TP=10, TN=15, FP=5, FN=10
SVM (Linear): Accuracy=0.5250, Precision=0.5238, Recall=0.5500, F1=0.5366
        TP=11, TN=10, FP=10, FN=9

===== Fold 3 =====
  -> Components to reach 95% variance: 28 components
RandomForest: Accuracy=0.7250, Precision=0.8462, Recall=0.5500, F1=0.6667
        TP=11, TN=18, FP=2, FN=9
SVM (Linear): Accuracy=0.5250, Precision=0.5455, Recall=0.3000, F1=0.3871
        TP=6, TN=15, FP=5, FN=14

===== Fold 4 =====
  -> Components to reach 95% variance: 22 components
RandomForest: Accuracy=0.4250, Precision=0.2857, Recall=0.1000, F1=0.1481
        TP=2, TN=15, FP=5, FN=18
SVM (Linear): Accuracy=0.4750, Precision=0.4615, Recall=0.3000, F1=0.3636
        TP=6, TN=13, FP=7, FN=14

===== Fold 5 =====
  -> Components to reach 95% variance: 20 components
RandomForest: Accuracy=0.6750, Precision=0.6667, Recall=0.7000, F1=0.6829
        TP=14, TN=13, FP=7, FN=6
SVM (Linear): Accuracy=0.5750, Precision=0.5556, Recall=0.7500, F1=0.6383
        TP=15, TN=8, FP=12, FN=5

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.6550, Precision=0.6695, Recall=0.5200, F1 Score=0.5760
  Avg TP=10.4, TN=15.8, FP=4.2, FN=9.6
  Avg PCA Components Used: 22.6
SVM (Linear):
  Accuracy=0.5800, Precision=0.5673, Recall=0.5600, F1 Score=0.5488
  Avg TP=11.2, TN=12.0, FP=8.0, FN=8.8
  Avg PCA Components Used: 22.6

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 35 components
RandomForest: Accuracy=0.8000, Precision=0.8750, Recall=0.7000, F1=0.7778
        TP=14, TN=18, FP=2, FN=6
SVM (Linear): Accuracy=0.6750, Precision=0.6667, Recall=0.7000, F1=0.6829
        TP=14, TN=13, FP=7, FN=6

===== Fold 2 =====
  -> Components to reach 98% variance: 37 components
RandomForest: Accuracy=0.6000, Precision=0.6250, Recall=0.5000, F1=0.5556
        TP=10, TN=14, FP=6, FN=10
SVM (Linear): Accuracy=0.6000, Precision=0.6250, Recall=0.5000, F1=0.5556
        TP=10, TN=14, FP=6, FN=10

===== Fold 3 =====
  -> Components to reach 98% variance: 43 components
RandomForest: Accuracy=0.6000, Precision=0.6250, Recall=0.5000, F1=0.5556
        TP=10, TN=14, FP=6, FN=10
SVM (Linear): Accuracy=0.6250, Precision=0.6667, Recall=0.5000, F1=0.5714
        TP=10, TN=15, FP=5, FN=10

===== Fold 4 =====
  -> Components to reach 98% variance: 36 components
RandomForest: Accuracy=0.4750, Precision=0.4444, Recall=0.2000, F1=0.2759
        TP=4, TN=15, FP=5, FN=16
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.1500, F1=0.2308
        TP=3, TN=17, FP=3, FN=17

===== Fold 5 =====
  -> Components to reach 98% variance: 35 components
RandomForest: Accuracy=0.4000, Precision=0.3333, Recall=0.2000, F1=0.2500
        TP=4, TN=12, FP=8, FN=16
SVM (Linear): Accuracy=0.3750, Precision=0.3333, Recall=0.2500, F1=0.2857
        TP=5, TN=10, FP=10, FN=15

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5750, Precision=0.5806, Recall=0.4200, F1 Score=0.4830
  Avg TP=8.4, TN=14.6, FP=5.4, FN=11.6
  Avg PCA Components Used: 37.2
SVM (Linear):
  Accuracy=0.5550, Precision=0.5583, Recall=0.4200, F1 Score=0.4653
  Avg TP=8.4, TN=13.8, FP=6.2, FN=11.6
  Avg PCA Components Used: 37.2

In [ ]:
print("\n### K-Fold + PCA - full_second ###")
run_kfold_with_pca(full_second)

### K-Fold + PCA - full_second ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 22 components
RandomForest: Accuracy=0.9500, Precision=1.0000, Recall=0.9000, F1=0.9474
        TP=18, TN=20, FP=0, FN=2
SVM (Linear): Accuracy=0.8250, Precision=0.8824, Recall=0.7500, F1=0.8108
        TP=15, TN=18, FP=2, FN=5

===== Fold 2 =====
  -> Components to reach 95% variance: 24 components
RandomForest: Accuracy=0.7000, Precision=0.7500, Recall=0.6000, F1=0.6667
        TP=12, TN=16, FP=4, FN=8
SVM (Linear): Accuracy=0.6500, Precision=0.7143, Recall=0.5000, F1=0.5882
        TP=10, TN=16, FP=4, FN=10

===== Fold 3 =====
  -> Components to reach 95% variance: 31 components
RandomForest: Accuracy=0.3500, Precision=0.3125, Recall=0.2500, F1=0.2778
        TP=5, TN=9, FP=11, FN=15
SVM (Linear): Accuracy=0.7250, Precision=0.7368, Recall=0.7000, F1=0.7179
        TP=14, TN=15, FP=5, FN=6

===== Fold 4 =====
  -> Components to reach 95% variance: 23 components
RandomForest: Accuracy=0.5750, Precision=0.7143, Recall=0.2500, F1=0.3704
        TP=5, TN=18, FP=2, FN=15
SVM (Linear): Accuracy=0.5750, Precision=0.6364, Recall=0.3500, F1=0.4516
        TP=7, TN=16, FP=4, FN=13

===== Fold 5 =====
  -> Components to reach 95% variance: 21 components
RandomForest: Accuracy=0.5750, Precision=0.5517, Recall=0.8000, F1=0.6531
        TP=16, TN=7, FP=13, FN=4
SVM (Linear): Accuracy=0.7000, Precision=0.6250, Recall=1.0000, F1=0.7692
        TP=20, TN=8, FP=12, FN=0

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.6300, Precision=0.6657, Recall=0.5600, F1 Score=0.5830
  Avg TP=11.2, TN=14.0, FP=6.0, FN=8.8
  Avg PCA Components Used: 24.2
SVM (Linear):
  Accuracy=0.6950, Precision=0.7190, Recall=0.6600, F1 Score=0.6676
  Avg TP=13.2, TN=14.6, FP=5.4, FN=6.8
  Avg PCA Components Used: 24.2

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 38 components
RandomForest: Accuracy=0.8500, Precision=1.0000, Recall=0.7000, F1=0.8235
        TP=14, TN=20, FP=0, FN=6
SVM (Linear): Accuracy=0.7250, Precision=0.6667, Recall=0.9000, F1=0.7660
        TP=18, TN=11, FP=9, FN=2

===== Fold 2 =====
  -> Components to reach 98% variance: 39 components
RandomForest: Accuracy=0.7250, Precision=0.7368, Recall=0.7000, F1=0.7179
        TP=14, TN=15, FP=5, FN=6
SVM (Linear): Accuracy=0.7500, Precision=0.7778, Recall=0.7000, F1=0.7368
        TP=14, TN=16, FP=4, FN=6

===== Fold 3 =====
  -> Components to reach 98% variance: 46 components
RandomForest: Accuracy=0.5500, Precision=0.5417, Recall=0.6500, F1=0.5909
        TP=13, TN=9, FP=11, FN=7
SVM (Linear): Accuracy=0.7500, Precision=0.7500, Recall=0.7500, F1=0.7500
        TP=15, TN=15, FP=5, FN=5

===== Fold 4 =====
  -> Components to reach 98% variance: 38 components
RandomForest: Accuracy=0.6000, Precision=1.0000, Recall=0.2000, F1=0.3333
        TP=4, TN=20, FP=0, FN=16
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.2000, F1=0.2857
        TP=4, TN=16, FP=4, FN=16

===== Fold 5 =====
  -> Components to reach 98% variance: 36 components
RandomForest: Accuracy=0.7000, Precision=0.6250, Recall=1.0000, F1=0.7692
        TP=20, TN=8, FP=12, FN=0
SVM (Linear): Accuracy=0.6500, Precision=0.6250, Recall=0.7500, F1=0.6818
        TP=15, TN=11, FP=9, FN=5

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.6850, Precision=0.7807, Recall=0.6500, F1 Score=0.6470
  Avg TP=13.0, TN=14.4, FP=5.6, FN=7.0
  Avg PCA Components Used: 39.4
SVM (Linear):
  Accuracy=0.6750, Precision=0.6639, Recall=0.6600, F1 Score=0.6441
  Avg TP=13.2, TN=13.8, FP=6.2, FN=6.8
  Avg PCA Components Used: 39.4

In [ ]:
print("\n### K-Fold + PCA - full (ทั้งตาราง) ###")
run_kfold_with_pca(full)

### K-Fold + PCA - full (ทั้งตาราง) ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 26 components
RandomForest: Accuracy=0.8875, Precision=0.9697, Recall=0.8000, F1=0.8767
        TP=32, TN=39, FP=1, FN=8
SVM (Linear): Accuracy=0.8375, Precision=0.8293, Recall=0.8500, F1=0.8395
        TP=34, TN=33, FP=7, FN=6

===== Fold 2 =====
  -> Components to reach 95% variance: 30 components
RandomForest: Accuracy=0.6125, Precision=0.6552, Recall=0.4750, F1=0.5507
        TP=19, TN=30, FP=10, FN=21
SVM (Linear): Accuracy=0.6125, Precision=0.6364, Recall=0.5250, F1=0.5753
        TP=21, TN=28, FP=12, FN=19

===== Fold 3 =====
  -> Components to reach 95% variance: 42 components
RandomForest: Accuracy=0.4875, Precision=0.4878, Recall=0.5000, F1=0.4938
        TP=20, TN=19, FP=21, FN=20
SVM (Linear): Accuracy=0.6125, Precision=0.5918, Recall=0.7250, F1=0.6517
        TP=29, TN=20, FP=20, FN=11

===== Fold 4 =====
  -> Components to reach 95% variance: 30 components
RandomForest: Accuracy=0.4625, Precision=0.3333, Recall=0.0750, F1=0.1224
        TP=3, TN=34, FP=6, FN=37
SVM (Linear): Accuracy=0.4250, Precision=0.2857, Recall=0.1000, F1=0.1481
        TP=4, TN=30, FP=10, FN=36

===== Fold 5 =====
  -> Components to reach 95% variance: 27 components
RandomForest: Accuracy=0.4500, Precision=0.4524, Recall=0.4750, F1=0.4634
        TP=19, TN=17, FP=23, FN=21
SVM (Linear): Accuracy=0.5000, Precision=0.5000, Recall=0.6500, F1=0.5652
        TP=26, TN=14, FP=26, FN=14

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
RandomForest:
  Accuracy=0.5800, Precision=0.5797, Recall=0.4650, F1 Score=0.5014
  Avg TP=18.6, TN=27.8, FP=12.2, FN=21.4
  Avg PCA Components Used: 31.0
SVM (Linear):
  Accuracy=0.5975, Precision=0.5686, Recall=0.5700, F1 Score=0.5560
  Avg TP=22.8, TN=25.0, FP=15.0, FN=17.2
  Avg PCA Components Used: 31.0

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 50 components
RandomForest: Accuracy=0.7625, Precision=0.9200, Recall=0.5750, F1=0.7077
        TP=23, TN=38, FP=2, FN=17
SVM (Linear): Accuracy=0.6250, Precision=0.6000, Recall=0.7500, F1=0.6667
        TP=30, TN=20, FP=20, FN=10

===== Fold 2 =====
  -> Components to reach 98% variance: 53 components
RandomForest: Accuracy=0.6000, Precision=0.6333, Recall=0.4750, F1=0.5429
        TP=19, TN=29, FP=11, FN=21
SVM (Linear): Accuracy=0.6375, Precision=0.6571, Recall=0.5750, F1=0.6133
        TP=23, TN=28, FP=12, FN=17

===== Fold 3 =====
  -> Components to reach 98% variance: 67 components
RandomForest: Accuracy=0.5625, Precision=0.5532, Recall=0.6500, F1=0.5977
        TP=26, TN=19, FP=21, FN=14
SVM (Linear): Accuracy=0.6625, Precision=0.6512, Recall=0.7000, F1=0.6747
        TP=28, TN=25, FP=15, FN=12

===== Fold 4 =====
  -> Components to reach 98% variance: 53 components
RandomForest: Accuracy=0.5125, Precision=0.5333, Recall=0.2000, F1=0.2909
        TP=8, TN=33, FP=7, FN=32
SVM (Linear): Accuracy=0.4500, Precision=0.3889, Recall=0.1750, F1=0.2414
        TP=7, TN=29, FP=11, FN=33

===== Fold 5 =====
  -> Components to reach 98% variance: 50 components
RandomForest: Accuracy=0.4500, Precision=0.4524, Recall=0.4750, F1=0.4634
        TP=19, TN=17, FP=23, FN=21
SVM (Linear): Accuracy=0.2875, Precision=0.0952, Recall=0.0500, F1=0.0656
        TP=2, TN=21, FP=19, FN=38

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
RandomForest:
  Accuracy=0.5775, Precision=0.6184, Recall=0.4750, F1 Score=0.5205
  Avg TP=19.0, TN=27.2, FP=12.8, FN=21.0
  Avg PCA Components Used: 54.6
SVM (Linear):
  Accuracy=0.5325, Precision=0.4785, Recall=0.4500, F1 Score=0.4523
  Avg TP=18.0, TN=24.6, FP=15.4, FN=22.0
  Avg PCA Components Used: 54.6