<a href="https://colab.research.google.com/github/sitthatkaja/ParkinsonAIModel/blob/main/%5BClassification%5D_Non_NormalFA_Sequential_Frames_(XGBoost).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [Classification] Non NormalFA Sequential Frames

This colab is a code for Classification (Parkinson or not) for ``` Sequential Frames in 3 Facial Action Scenario following: Non-Smile, Smile, and Combine``` introducing methodology.

***Note: if you have any problem please check in my github: https://github.com/sitthatkaja/ParkinsonAIModel***

---

## 1. Data Input
---

This section you need to input data form data collect in github. This setep is depend on user. You can use  ``` Google sheet link with google Drive ``` to import Data.

***Note: This section is not to shown because a privacy of account.***

## 2. Data Preprocessing
---

Form my input this is sliding video to half for  `3 Facial Action Scenarios following: Non-Smile, Smile, and Combine` that is mean the data should be counting of half it (106350 Columns in Sequential Frame)


***note: This method have something wrong or error of colab including: number of column. you can ignore it.***

In [ ]:
for i in range(1, len(dfs) + 1):
    globals()[f'df{i}'] = dfs[f'df{i}']

In [ ]:
dfss = [globals()[f'df{i}'] for i in range(1, len(dfs) + 1)]

In [ ]:
print(len(dfss))

400

In [ ]:
for i in range(len(dfss)):
    dfss[i] = dfss[i].iloc[:, 5:]

In [ ]:
dfss[0].head()

,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,eye_lmk_x_0,eye_lmk_x_1,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,0.206,434.9,440.2,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
1,0.179208,0.177269,-0.967709,-0.160462,0.249239,-0.955056,0.010,0.218,431.5,437.4,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
2,0.175176,0.168792,-0.969960,-0.153304,0.236380,-0.959491,0.011,0.207,429.7,436.2,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,0.178275,0.167154,-0.969679,-0.161075,0.229773,-0.959823,0.009,0.203,428.4,434.5,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,0.185327,0.163628,-0.968958,-0.151368,0.231574,-0.960969,0.018,0.202,427.5,433.4,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [ ]:
for i in range(len(dfss)):
    df = dfss[i]
    # รวมแถวทั้งหมดให้เป็น 1 row
    flattened_row = pd.concat([df.iloc[j] for j in range(len(df))]).reset_index(drop=True)

    # แปลงกลับเป็น DataFrame ที่มี 1 แถว
    dfss[i] = pd.DataFrame([flattened_row])

In [ ]:
combined_df = pd.concat(dfss, axis=0).reset_index(drop=True)
combined_df

,0,1,2,3,4,5,6,7,8,9,...,319040,319041,319042,319043,319044,319045,319046,319047,319048,319049
0,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,0.206,434.9,440.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.165000,0.281527,-0.945261,-0.105064,0.266013,-0.958227,0.031,0.280,396.0,402.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.141283,0.305359,-0.941698,-0.102089,0.303798,-0.947251,0.021,0.312,469.2,475.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.109993,0.249438,-0.962124,-0.185233,0.327856,-0.926390,-0.040,0.297,369.4,372.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.207585,0.273623,-0.939169,-0.065616,0.329009,-0.942044,0.075,0.310,376.9,382.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.017815,0.229241,-0.973207,-0.063155,0.209498,-0.975767,-0.023,0.221,461.5,466.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,0.030628,0.194938,-0.980337,-0.067250,0.160477,-0.984746,-0.019,0.179,484.6,490.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,0.022909,0.186868,-0.982118,-0.039888,0.170034,-0.984631,-0.009,0.180,476.9,482.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,0.029517,0.219635,-0.975135,-0.054893,0.164015,-0.984929,-0.013,0.193,460.9,466.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,0.037639,0.247780,-0.968085,-0.038300,0.204927,-0.978028,-0.000,0.229,471.2,476.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
full = combined_df.iloc[:,:106350]
full

,0,1,2,3,4,5,6,7,8,9,...,104213,104214,104215,104216,104217,104218,104219,104220,104221,104222
0,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,0.206,434.9,440.2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.165000,0.281527,-0.945261,-0.105064,0.266013,-0.958227,0.031,0.280,396.0,402.2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.141283,0.305359,-0.941698,-0.102089,0.303798,-0.947251,0.021,0.312,469.2,475.6,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,0.109993,0.249438,-0.962124,-0.185233,0.327856,-0.926390,-0.040,0.297,369.4,372.8,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,0.207585,0.273623,-0.939169,-0.065616,0.329009,-0.942044,0.075,0.310,376.9,382.3,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0.017815,0.229241,-0.973207,-0.063155,0.209498,-0.975767,-0.023,0.221,461.5,466.9,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
396,0.030628,0.194938,-0.980337,-0.067250,0.160477,-0.984746,-0.019,0.179,484.6,490.4,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
397,0.022909,0.186868,-0.982118,-0.039888,0.170034,-0.984631,-0.009,0.180,476.9,482.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
398,0.029517,0.219635,-0.975135,-0.054893,0.164015,-0.984929,-0.013,0.193,460.9,466.1,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
399,0.037639,0.247780,-0.968085,-0.038300,0.204927,-0.978028,-0.000,0.229,471.2,476.6,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
full.isnull().values.any()

np.False_

## 3. Modeling
---
This section is Modeling when you prepare data form data preprocessing. This method, You should to try setup form other side and coding following: PCA and 3 Models.

***Note: This section in for experimental for all. It's means some value is non-using for report.***

3.1 NO PCA

---

In [ ]:
status = df[['Paror1Healthy0', 'kfold','ForS']]
status

     Paror1Healthy0  kfold  ForS
0                 1      1     1
1                 1      1     1
2                 1      1     1
3                 1      1     1
4                 1      1     1
..              ...    ...   ...
395               0      5     2
396               0      5     2
397               0      5     2
398               0      5     2
399               0      5     2

[400 rows x 3 columns]

In [ ]:
full = pd.concat([status,full], axis=1)
full

,Paror1Healthy0,kfold,ForS,0,1,2,3,4,5,6,...,104213,104214,104215,104216,104217,104218,104219,104220,104221,104222
0,1,1,1,0.174402,0.173605,-0.969250,-0.139685,0.230682,-0.962951,0.018,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,1,1,1,0.165000,0.281527,-0.945261,-0.105064,0.266013,-0.958227,0.031,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1,1,1,0.141283,0.305359,-0.941698,-0.102089,0.303798,-0.947251,0.021,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,1,1,1,0.109993,0.249438,-0.962124,-0.185233,0.327856,-0.926390,-0.040,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,1,1,1,0.207585,0.273623,-0.939169,-0.065616,0.329009,-0.942044,0.075,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,5,2,0.017815,0.229241,-0.973207,-0.063155,0.209498,-0.975767,-0.023,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
396,0,5,2,0.030628,0.194938,-0.980337,-0.067250,0.160477,-0.984746,-0.019,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
397,0,5,2,0.022909,0.186868,-0.982118,-0.039888,0.170034,-0.984631,-0.009,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
398,0,5,2,0.029517,0.219635,-0.975135,-0.054893,0.164015,-0.984929,-0.013,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
399,0,5,2,0.037639,0.247780,-0.968085,-0.038300,0.204927,-0.978028,-0.000,...,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

In [ ]:
# แยก full ตาม ForS
full_first = full[full['ForS'] == 1].reset_index(drop=True)
full_second = full[full['ForS'] == 2].reset_index(drop=True)
# full เดิมคือทั้งครึ่งแรกและครึ่งหลัง

In [ ]:
def run_kfold_no_pca(df, target_col='Paror1Healthy0', kfold_col='kfold'):
    models = {
    "XGBoost": xgb.XGBClassifier(tree_method='gpu_hist')
    }

    results = {name: {
        "accuracy": [], "precision": [], "recall": [], "f1": [],
        "TP": [], "TN": [], "FP": [], "FN": []
    } for name in models}

    for fold in range(1, 6):
        print(f"\n===== Fold {fold} =====")
        df_train = df[df[kfold_col] != fold].reset_index(drop=True)
        df_valid = df[df[kfold_col] == fold].reset_index(drop=True)

        # ดรอป target, kfold, ForS (ถ้ามี) ออกจาก X
        drop_cols = [target_col, kfold_col]
        if 'ForS' in df.columns:
            drop_cols.append('ForS')

        X_train = df_train.drop(columns=drop_cols)
        y_train = df_train[target_col]
        X_valid = df_valid.drop(columns=drop_cols)
        y_valid = df_valid[target_col]

        for name, model in models.items():
            model.fit(X_train, y_train)
            preds = model.predict(X_valid)

            accuracy = accuracy_score(y_valid, preds)
            precision = precision_score(y_valid, preds, average='binary')
            recall = recall_score(y_valid, preds, average='binary')
            f1 = f1_score(y_valid, preds, average='binary')
            tn, fp, fn, tp = confusion_matrix(y_valid, preds).ravel()

            results[name]["accuracy"].append(accuracy)
            results[name]["precision"].append(precision)
            results[name]["recall"].append(recall)
            results[name]["f1"].append(f1)
            results[name]["TP"].append(tp)
            results[name]["TN"].append(tn)
            results[name]["FP"].append(fp)
            results[name]["FN"].append(fn)

            print(f"{name}: Accuracy={accuracy:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
            print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

    # สรุปค่าเฉลี่ยแต่ละโมเดล
    print("\n===== Average Performance Across 5 Folds =====")
    for name in models:
        avg_acc = sum(results[name]["accuracy"]) / 5
        avg_prec = sum(results[name]["precision"]) / 5
        avg_rec = sum(results[name]["recall"]) / 5
        avg_f1 = sum(results[name]["f1"]) / 5
        avg_tp = sum(results[name]["TP"]) / 5
        avg_tn = sum(results[name]["TN"]) / 5
        avg_fp = sum(results[name]["FP"]) / 5
        avg_fn = sum(results[name]["FN"]) / 5

        print(f"{name}:")
        print(f"  Accuracy={avg_acc:.4f}, Precision={avg_prec:.4f}, Recall={avg_rec:.4f}, F1 Score={avg_f1:.4f}")
        print(f"  Avg TP={avg_tp:.1f}, TN={avg_tn:.1f}, FP={avg_fp:.1f}, FN={avg_fn:.1f}")

In [ ]:
print("\n### K-Fold (No PCA) - full_first ###")
run_kfold_no_pca(full_first)

In [ ]:
print("\n### K-Fold (No PCA) - full_second ###")
run_kfold_no_pca(full_second)

In [ ]:
print("\n### K-Fold (No PCA) - full (ทั้งตาราง) ###")
run_kfold_no_pca(full)

### K-Fold (No PCA) - full (ทั้งตาราง) ###

===== Fold 1 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:46:08] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:46:55] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:46:57] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.8375, Precision=0.8857, Recall=0.7750, F1=0.8267
        TP=31, TN=36, FP=4, FN=9

===== Fold 2 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:47:32] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:48:19] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.6250, Precision=0.6087, Recall=0.7000, F1=0.6512
        TP=28, TN=22, FP=18, FN=12

===== Fold 3 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:48:53] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:49:41] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.5375, Precision=0.5294, Recall=0.6750, F1=0.5934
        TP=27, TN=16, FP=24, FN=13

===== Fold 4 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:50:22] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:51:09] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.4625, Precision=0.4118, Recall=0.1750, F1=0.2456
        TP=7, TN=30, FP=10, FN=33

===== Fold 5 =====

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:51:44] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [15:52:31] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

XGBoost: Accuracy=0.5125, Precision=0.5135, Recall=0.4750, F1=0.4935
        TP=19, TN=22, FP=18, FN=21

===== Average Performance Across 5 Folds =====
XGBoost:
  Accuracy=0.5950, Precision=0.5898, Recall=0.5600, F1 Score=0.5621
  Avg TP=22.4, TN=25.2, FP=14.8, FN=17.6

---
#### 3.2 PCA 95% and 98% variance

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import numpy as np

def run_kfold_with_pca(df, target_col='Paror1Healthy0', kfold_col='kfold', variances=[0.95, 0.98]):
    models = {
        "XGBoost": xgb.XGBClassifier(tree_method='hist')
    }

    for var in variances:
        print(f"\n===== PCA with Explained Variance = {var} =====")
        results = {name: [] for name in models.keys()}

        for fold in range(1, 6):
            print(f"\n===== Fold {fold} =====")
            train_df = df[df[kfold_col] != fold].reset_index(drop=True)
            valid_df = df[df[kfold_col] == fold].reset_index(drop=True)

            drop_cols = [target_col, kfold_col]
            if 'ForS' in df.columns:
                drop_cols.append('ForS')

            X_train = train_df.drop(columns=drop_cols).values
            y_train = train_df[target_col].values
            X_valid = valid_df.drop(columns=drop_cols).values
            y_valid = valid_df[target_col].values

            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_valid_scaled = scaler.transform(X_valid)

            pca = PCA(n_components=var)
            X_train_pca = pca.fit_transform(X_train_scaled)
            X_valid_pca = pca.transform(X_valid_scaled)

            n_components_used = X_train_pca.shape[1]
            print(f"  -> Components to reach {var*100:.0f}% variance: {n_components_used} components")

            for name, model in models.items():
                model.fit(X_train_pca, y_train)
                y_pred = model.predict(X_valid_pca)

                acc = accuracy_score(y_valid, y_pred)
                f1 = f1_score(y_valid, y_pred)
                recall = recall_score(y_valid, y_pred)
                precision = precision_score(y_valid, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_valid, y_pred).ravel()

                results[name].append({
                    'fold': fold,
                    'n_components': n_components_used,
                    'accuracy': acc,
                    'f1_score': f1,
                    'recall': recall,
                    'precision': precision,
                    'tn': tn,
                    'fp': fp,
                    'fn': fn,
                    'tp': tp
                })

                print(f"{name}: Accuracy={acc:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")
                print(f"        TP={tp}, TN={tn}, FP={fp}, FN={fn}")

        # สรุปค่าเฉลี่ย
        print(f"\n===== Average Performance Across 5 Folds (Explained Variance = {var}) =====")
        for name in results:
            accuracies = [r['accuracy'] for r in results[name]]
            f1s = [r['f1_score'] for r in results[name]]
            recalls = [r['recall'] for r in results[name]]
            precisions = [r['precision'] for r in results[name]]
            tns = [r['tn'] for r in results[name]]
            fps = [r['fp'] for r in results[name]]
            fns = [r['fn'] for r in results[name]]
            tps = [r['tp'] for r in results[name]]
            components = [r['n_components'] for r in results[name]]

            print(f"{name}:")
            print(f"  Accuracy={np.mean(accuracies):.4f}, Precision={np.mean(precisions):.4f}, Recall={np.mean(recalls):.4f}, F1 Score={np.mean(f1s):.4f}")
            print(f"  Avg TP={np.mean(tps):.1f}, TN={np.mean(tns):.1f}, FP={np.mean(fps):.1f}, FN={np.mean(fns):.1f}")
            print(f"  Avg PCA Components Used: {np.mean(components):.1f}")

In [ ]:
print("\n### K-Fold + PCA - full_first ###")
run_kfold_with_pca(full_first)

### K-Fold + PCA - full_first ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 22 components
XGBoost: Accuracy=0.8250, Precision=0.7826, Recall=0.9000, F1=0.8372
        TP=18, TN=15, FP=5, FN=2

===== Fold 2 =====
  -> Components to reach 95% variance: 25 components
XGBoost: Accuracy=0.5250, Precision=0.5333, Recall=0.4000, F1=0.4571
        TP=8, TN=13, FP=7, FN=12

===== Fold 3 =====
  -> Components to reach 95% variance: 30 components
XGBoost: Accuracy=0.4750, Precision=0.4762, Recall=0.5000, F1=0.4878
        TP=10, TN=9, FP=11, FN=10

===== Fold 4 =====
  -> Components to reach 95% variance: 24 components
XGBoost: Accuracy=0.6250, Precision=0.7778, Recall=0.3500, F1=0.4828
        TP=7, TN=18, FP=2, FN=13

===== Fold 5 =====
  -> Components to reach 95% variance: 22 components
XGBoost: Accuracy=0.6750, Precision=0.7059, Recall=0.6000, F1=0.6486
        TP=12, TN=15, FP=5, FN=8

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
XGBoost:
  Accuracy=0.6250, Precision=0.6552, Recall=0.5500, F1 Score=0.5827
  Avg TP=11.0, TN=14.0, FP=6.0, FN=9.0
  Avg PCA Components Used: 24.6

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 36 components
XGBoost: Accuracy=0.6750, Precision=0.6296, Recall=0.8500, F1=0.7234
        TP=17, TN=10, FP=10, FN=3

===== Fold 2 =====
  -> Components to reach 98% variance: 39 components
XGBoost: Accuracy=0.7250, Precision=0.9091, Recall=0.5000, F1=0.6452
        TP=10, TN=19, FP=1, FN=10

===== Fold 3 =====
  -> Components to reach 98% variance: 46 components
XGBoost: Accuracy=0.5000, Precision=0.5000, Recall=0.5000, F1=0.5000
        TP=10, TN=10, FP=10, FN=10

===== Fold 4 =====
  -> Components to reach 98% variance: 38 components
XGBoost: Accuracy=0.4500, Precision=0.4286, Recall=0.3000, F1=0.3529
        TP=6, TN=12, FP=8, FN=14

===== Fold 5 =====
  -> Components to reach 98% variance: 37 components
XGBoost: Accuracy=0.2750, Precision=0.0000, Recall=0.0000, F1=0.0000
        TP=0, TN=11, FP=9, FN=20

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
XGBoost:
  Accuracy=0.5250, Precision=0.4935, Recall=0.4300, F1 Score=0.4443
  Avg TP=8.6, TN=12.4, FP=7.6, FN=11.4
  Avg PCA Components Used: 39.2

In [ ]:
print("\n### K-Fold + PCA - full_second ###")
run_kfold_with_pca(full_second)

### K-Fold + PCA - full_second ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 26 components
XGBoost: Accuracy=0.9500, Precision=0.9500, Recall=0.9500, F1=0.9500
        TP=19, TN=19, FP=1, FN=1

===== Fold 2 =====
  -> Components to reach 95% variance: 28 components
XGBoost: Accuracy=0.6000, Precision=0.5909, Recall=0.6500, F1=0.6190
        TP=13, TN=11, FP=9, FN=7

===== Fold 3 =====
  -> Components to reach 95% variance: 33 components
XGBoost: Accuracy=0.5750, Precision=0.6000, Recall=0.4500, F1=0.5143
        TP=9, TN=14, FP=6, FN=11

===== Fold 4 =====
  -> Components to reach 95% variance: 26 components
XGBoost: Accuracy=0.7500, Precision=0.7500, Recall=0.7500, F1=0.7500
        TP=15, TN=15, FP=5, FN=5

===== Fold 5 =====
  -> Components to reach 95% variance: 24 components
XGBoost: Accuracy=0.6250, Precision=0.6000, Recall=0.7500, F1=0.6667
        TP=15, TN=10, FP=10, FN=5

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
XGBoost:
  Accuracy=0.7000, Precision=0.6982, Recall=0.7100, F1 Score=0.7000
  Avg TP=14.2, TN=13.8, FP=6.2, FN=5.8
  Avg PCA Components Used: 27.4

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 41 components
XGBoost: Accuracy=0.9500, Precision=0.9500, Recall=0.9500, F1=0.9500
        TP=19, TN=19, FP=1, FN=1

===== Fold 2 =====
  -> Components to reach 98% variance: 42 components
XGBoost: Accuracy=0.5750, Precision=0.5789, Recall=0.5500, F1=0.5641
        TP=11, TN=12, FP=8, FN=9

===== Fold 3 =====
  -> Components to reach 98% variance: 49 components
XGBoost: Accuracy=0.6250, Precision=0.6471, Recall=0.5500, F1=0.5946
        TP=11, TN=14, FP=6, FN=9

===== Fold 4 =====
  -> Components to reach 98% variance: 42 components
XGBoost: Accuracy=0.6000, Precision=0.6429, Recall=0.4500, F1=0.5294
        TP=9, TN=15, FP=5, FN=11

===== Fold 5 =====
  -> Components to reach 98% variance: 39 components
XGBoost: Accuracy=0.5750, Precision=0.5789, Recall=0.5500, F1=0.5641
        TP=11, TN=12, FP=8, FN=9

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
XGBoost:
  Accuracy=0.6650, Precision=0.6796, Recall=0.6100, F1 Score=0.6404
  Avg TP=12.2, TN=14.4, FP=5.6, FN=7.8
  Avg PCA Components Used: 42.6

In [ ]:
print("\n### K-Fold + PCA - full (ทั้งตาราง) ###")
run_kfold_with_pca(full)

### K-Fold + PCA - full (ทั้งตาราง) ###

===== PCA with Explained Variance = 0.95 =====

===== Fold 1 =====
  -> Components to reach 95% variance: 32 components
XGBoost: Accuracy=0.8250, Precision=0.8824, Recall=0.7500, F1=0.8108
        TP=30, TN=36, FP=4, FN=10

===== Fold 2 =====
  -> Components to reach 95% variance: 36 components
XGBoost: Accuracy=0.5625, Precision=0.6190, Recall=0.3250, F1=0.4262
        TP=13, TN=32, FP=8, FN=27

===== Fold 3 =====
  -> Components to reach 95% variance: 46 components
XGBoost: Accuracy=0.5000, Precision=0.5000, Recall=0.4750, F1=0.4872
        TP=19, TN=21, FP=19, FN=21

===== Fold 4 =====
  -> Components to reach 95% variance: 35 components
XGBoost: Accuracy=0.5125, Precision=0.5263, Recall=0.2500, F1=0.3390
        TP=10, TN=31, FP=9, FN=30

===== Fold 5 =====
  -> Components to reach 95% variance: 31 components
XGBoost: Accuracy=0.4500, Precision=0.4524, Recall=0.4750, F1=0.4634
        TP=19, TN=17, FP=23, FN=21

===== Average Performance Across 5 Folds (Explained Variance = 0.95) =====
XGBoost:
  Accuracy=0.5700, Precision=0.5960, Recall=0.4550, F1 Score=0.5053
  Avg TP=18.2, TN=27.4, FP=12.6, FN=21.8
  Avg PCA Components Used: 36.0

===== PCA with Explained Variance = 0.98 =====

===== Fold 1 =====
  -> Components to reach 98% variance: 56 components
XGBoost: Accuracy=0.6750, Precision=0.7059, Recall=0.6000, F1=0.6486
        TP=24, TN=30, FP=10, FN=16

===== Fold 2 =====
  -> Components to reach 98% variance: 60 components
XGBoost: Accuracy=0.6125, Precision=0.6667, Recall=0.4500, F1=0.5373
        TP=18, TN=31, FP=9, FN=22

===== Fold 3 =====
  -> Components to reach 98% variance: 73 components
XGBoost: Accuracy=0.3750, Precision=0.3864, Recall=0.4250, F1=0.4048
        TP=17, TN=13, FP=27, FN=23

===== Fold 4 =====
  -> Components to reach 98% variance: 59 components
XGBoost: Accuracy=0.5500, Precision=0.5833, Recall=0.3500, F1=0.4375
        TP=14, TN=30, FP=10, FN=26

===== Fold 5 =====
  -> Components to reach 98% variance: 55 components
XGBoost: Accuracy=0.4375, Precision=0.4286, Recall=0.3750, F1=0.4000
        TP=15, TN=20, FP=20, FN=25

===== Average Performance Across 5 Folds (Explained Variance = 0.98) =====
XGBoost:
  Accuracy=0.5300, Precision=0.5542, Recall=0.4400, F1 Score=0.4856
  Avg TP=17.6, TN=24.8, FP=15.2, FN=22.4
  Avg PCA Components Used: 60.6